### ISSUE TITLE
XBEs with blank title names have the incorrect name displayed.

### ISSUE THREAD

**Issue by InternalLoss** [Cxbx-Reloaded/Cxbx-Reloaded#2344] opened 2022-04-08 16:32 UTC
## Quick summary
When loading an XBE with no title name (such as TQ-040 v2 - "The Incredibles"), Cxbx-Reloaded incorrectly shows the folder name or filename.

## Details

Screenshot attached - the XBE is in my Desktop folder and thus shows this:

![image](https://user-images.githubusercontent.com/30775249/162483851-b5dd053d-f4bd-4ba6-be2f-aa45d49c8ba3.png)

If the name is changed (such as to "test.name.xbe"), "test.name" is shown:
![image](https://user-images.githubusercontent.com/30775249/162483942-59b9ab39-9c60-4aac-80fb-15b365f41a97.png)

### System Configuration:

* OS: Windows 11 Pro 21H2 (Build 22000.593)
* CPU: Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz   3.40 GHz
* GPU: N/A, but Intel's built in GPU.

### Additional Information (if any):
N/A

**Comment by RadWolfie** [comment] 2022-04-08 22:05
This is a feature of pull request #719 when title doesn't have title name embedded inside xbe file. Which then will fall back to non-default name of file, and finally to the folder's name. According to your results given are correct by design and therefore won't be fixed.

Title's content extraction from dumps are expected to be in its own folder. Which in this case, "The Incredibles" folder.

**Closed by RadWolfie** 2022-04-08 22:05 UTC

**Comment by PatrickvL** [comment] 2022-04-08 22:53
Also, @InternalLoss what would be the "correct" name to show? Where would CxbxReloaded get it from?

**Comment by LukeUsher** [comment] 2022-04-09 08:53
I think it was too hasty to close this issue as invalid: many emulators solve this problem by embedding a game database, for example, so the name is always correct for known titles: this is useful as the XBE title is often *not* the correct name of the game, since on a retail Xbox it was never shown anywhere to the end-user.

A large number of XBEs online only have valid titles because they have been modified to show friendly names in hacked dashboards; from a disc, most of these don't as friendly names; for this a game database could be the best solution.

**Comment by PatrickvL** [comment] 2022-04-09 09:45
Are you suggesting to include everything in the compatibility database and use that as an override title? Or query the website when no title is found? https://cxbx-reloaded.co.uk/compatibility/title/513
