### ISSUE TITLE
Dashboard Memory Management screen erroneously detects a memory unit

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#219] opened 2017-03-10 16:55 UTC
@LukeUsher 

> The only part of the dashboard that is still broken (aside from graphics) is the memory management screen
> Our controller/memory device emulation is very poor, that will work once we solve that
> I didn't look into it too much, but we definitely have/had an issue where the controller code in Cxbx reports that a new controller has been connected every single time a game asks for devices, rather than just the first check
> This causes a loop in the dashboard because when a new controller is connected, it is polled to detect attached memory units as they connect to the controllers
> (An xbox pad has an internal USB hub, with two ports exposed for memory units, and one port wired to the actual controller)
> I haven't fixed it yet because I'm not sure what the right thing to do is
> I fear modifying it could break controllers in other software

**Comment by LukeUsher** [comment] 2017-03-11 19:41
Sorry about that, it seems that I already fixed the above issue in a previous commit, can't remember which one specifically but it is not a problem in the latest build.

This issue can stay though, as it still doesn't function properly (always seems to show that there's no data)

**Comment by LukeUsher** [comment] 2017-08-01 18:31
This has partially been fixed in #571, the dashboard memory management screen still functions.
The memory unit is still erroneously detected.

**Comment by PatrickvL** [comment] 2017-10-29 14:28
@LukeUsher Is this now fixed? If so, please close this issue.

**Comment by RadWolfie** [comment] 2017-10-29 18:57
I don't see this problem in [4920] dashboard. Other dashboards 4034 and 4817 are not bootable at the moment due to "QuinCunx is unsupported (temporarily)" error. When I bypass it, I don't see a memory unit icon or selection on both dashboards. I believe the issue is resolved.

**Comment by LukeUsher** [comment] 2017-10-29 19:13
My bad, this has been solved since the recent XInput Work (GetDeviceType/deriving XINPUT_TYPE_GAMEPAD)

**Closed by LukeUsher** 2017-10-29 19:13 UTC
Labels: controller
