### ISSUE TITLE
Create a website for the Cxbx-Reloaded project

### ISSUE THREAD

**Issue by AzurikRiseOfPerathia** [Cxbx-Reloaded/Cxbx-Reloaded#1732] opened 2019-09-19 11:35 UTC

**Comment by LukeUsher** [comment] 2019-09-19 13:28
There is a plan for a website already, including 'news' blog, compatibility database, setup-guide, and downloads of history/current builds.

The problem is there are only a limited number of us developers, and we'd much prefer to improve emulation than spending several weeks-months perfecting the website.

If we had more man-power, I could take a break to concentrate on the website, but for now, we have to prioritise the emulator itself.

**Comment by RadWolfie** [comment] 2019-09-20 01:33
@LukeUsher We still am getting **"where's the download link?"** in discord for very long time. If static webpages aren't ready, then it may be time to start using [GitHub Pages](https://pages.github.com/) feature with the basic details.

**Comment by DANIELDEV22** [comment] 2020-03-27 22:23
Hi I am a Wordpress developer if I can help in something just let me know, I know a moderate amount of php, html, javascript and css. Im willing to help the cause for a website, feel free to reach me out here  -> DanielSebastian1920@gmail.com

**Comment by ergo720** [comment] 2020-11-29 16:22
A website for cxbxr has been created now and it's available at https://cxbx-reloaded.co.uk/ so closing this.

**Closed by ergo720** 2020-11-29 16:22 UTC
Labels: deployment, low-priority

**Comment by AzurikRiseOfPerathia** [comment] 2020-12-25 21:48
I analyzed the site, there are still a lot of games missing

this list will be updated when I check the new list (I am at 244 games currently.)

AFL Premiership 2005
Alfa Romeo Racing Italiano
Club Football 2005: Leeds United
Club Football: Birmingham City
Club Football: Marseille 
Club Football: Milan 
Club Football: Newcastle United 
Club Football: Paris Saint-Germain 
Crash N Burn
Daemon Vector

**Comment by PatrickvL** [comment] 2020-12-25 21:53
10 missing out of 244 checked is only 4,46% - not "a lot", but thanks for the effort, I'm sure they'll be added sooner or later

**Comment by AzurikRiseOfPerathia** [comment] 2020-12-25 21:55
You're welcome ; ) 
I will continue tomorrow rummaging through the long list that I have in my possession

**Comment by AzurikRiseOfPerathia** [comment] 2020-12-26 14:34
Normally this exit can be closed permanently
