### ISSUE TITLE
dino crisis 3 crash

### ISSUE THREAD

**Issue by mystro1213** [Cxbx-Reloaded/Cxbx-Reloaded#487] opened 2017-06-09 21:34 UTC
game crashes after i start and take difficulty 
![bandicam 2017-06-09 14-29-27-041](https://user-images.githubusercontent.com/24327966/26995261-82fcab92-4d20-11e7-9078-6a70ae7d6922.jpg)
xbe info
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1065296/Xbe.txt)

**Comment by PatrickvL** [comment] 2017-08-04 14:35
Duplicate of #416

**Closed by PatrickvL** 2017-08-04 14:35 UTC
Labels: game-compatibility
