### ISSUE TITLE
Its not possible to play game form Windows share.

### ISSUE THREAD

**Issue by ruthan** [Cxbx-Reloaded/Cxbx-Reloaded#1625] opened 2019-06-01 12:58 UTC
Im using network share for share for sharing my images for multiple machine, its working well with 95% of adavanced emulators with but this one.
I get always fatal error, that is not possible to open *.xbe file, when i start the emulation from network share.

**Comment by Margen67** [comment] 2019-06-01 13:29
Duplicate of #1450

**Closed** 2019-06-02 00:02 UTC
Labels: duplicate
