### ISSUE TITLE
[PAL] Colin McRae Rally 2005 - crashes during startup

### ISSUE THREAD

**Issue by rexcaptain501** [Cxbx-Reloaded/Cxbx-Reloaded#535] opened 2017-07-28 00:43 UTC
Tested on Cxbx-Reloaded build a8033fee, Jul 27 2017

Creating startup crash issue on request of @RadWolfie.

Crash: ![cmr05](https://user-images.githubusercontent.com/10300935/28697723-064563c6-7392-11e7-9efd-9d55c977835b.PNG)

.xbe info: [Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1181652/Xbe.txt)

Kernel Debug file: [KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1181653/KrnlDebug.txt)

**Comment by RadWolfie** [comment] 2017-07-28 01:25
It has regress for no audio after merge audio improvement.

After reviewing the message of CDirectSoundVoice_SetMixBinsVolume + 0xd6 at the crash. By going back 2 caller functions, I have discovered a missing patch for this title which I think is IDirectSoundBuffer_SetNotificationPositions. Since the passdown on the first call show these params.
1. pX_CDirectSoundBuffer
2. 0x00000001
3. appears to be a pointer of CDSBPOSITIONNOTIFY containing -1 and a handle.

By adding **`IDirectSoundBuffer_SetNotificationPositions=21eb15`** to HLE cache file, it start to play two intros which is currently show no video. Then show light gray color background.

Can one of the dev team verify this patch is indeed "IDirectSoundBuffer_SetNotificationPositions"?

**Comment by jackchentwkh** [comment] 2017-07-28 04:59
one should be able to compare the HLE cache file generated before and after the regression to see the differences.

**Comment by PatrickvL** [comment] 2017-07-28 06:13
If this is a regression, then yeah, the contents of the HLE cache file could be compared between "git bisect" steps, but I fear that might show many differences (especially when OOVPA updates have been merged in).
Anyway, on which commit did it still work?

**Comment by RadWolfie** [comment] 2017-07-28 14:15
It is not regressing for HLE cache, I believe it made a regress because of old DirectSoundDoWork's audio hack force the audio to play no matter what even if play/pause function has not triggered. Once I added IDirectSoundBuffer_SetNotificationPositions to HLE cache. The title is able to continue further than before plus is playing audio after the original crash. Plus I want to remind what @rexcaptain501 mention, it made a regress right after HLE-Audio-Improvement merge. Inside HLE-Audio-Improvement, there are absolutely no HLE database changes, only DirectSound internal changes. I hope this clear things up.

**Comment by PatrickvL** [comment] 2017-07-28 22:12
So you still need help with this? If so, then what must be done exactly?

**Comment by RadWolfie** [comment] 2017-07-29 00:31
I have a strong feeling this exception, 100% for sure, is IDirectSoundBuffer_SetNotificationPositions which is missing from dsound's HLE database. Since I am not familiar with OOPVA method, I went ahead find existing OOPVA signature and try it from there. Turn out OOPVA 4627 for IDirectSoundBuffer_SetNotificationPositions and CDirectSoundBuffer_SetNotificationPositions are outputing the same location I suspect might be it. I can add this existing OOPVA signature to 5344, 5558, and 5849.


Since this title is 5849 lib, then it is also possible be affecting Lego Star Wars, Lego Star Wars 2, and Star Wars KotoR 2 titles as well.

**Comment by PatrickvL** [comment] 2017-08-15 11:19
This issue was moved to Cxbx-Reloaded/game-compatibility#74

**Closed by PatrickvL** 2017-08-15 11:19 UTC
Labels: game-compatibility, regression
