### ISSUE TITLE
cxbx interface issue

### ISSUE THREAD

**Issue by medievil1** [Cxbx-Reloaded/Cxbx-Reloaded#2272] opened 2021-08-02 02:20 UTC
## Quick summary

after starting emulation with logging on, the LOG:(method) drops down a line on the interface instead of remaining beside the HLE status

## Details

as above, the LOG:(method) adds a line to the interface after emulation starts

### System Configuration:

* OS - windows 11 pro(dev build)
* CPU - i5 9600k
* GPU- GTX 1660
* etc.

### Additional Information (if any):
Possibly DPI dependent

Screenshot
![image](https://user-images.githubusercontent.com/38597905/127796094-281011cb-58d3-4c8d-a06b-8c0dcee06696.png)

**Comment by RadWolfie** [comment] 2021-08-02 13:19
I am unable to reproduce the issue. I recently notice you have Windows 11 dev build as your OS. We do not provide any support for OS that are in development, even insider access build too.

**Comment by ergo720** [comment] 2021-08-07 12:34
I tried to reproduce the issue on Win10 and I couldn't either, so I'm going to close this for now as "not reproducible", as this might be a user-specific issue. One thing I notice is that your window seems to be too small, since your FPS counter is much closer to the help menu than mine.

![Capture](https://user-images.githubusercontent.com/45463469/128600186-e9ae87f6-d6aa-4a58-8dcb-ee60cc306114.PNG)

**Closed by ergo720** 2021-08-07 12:34 UTC
Labels: bug, user interface

**Comment by medievil1** [comment] 2021-08-07 12:51
thats why I mentioned DPI specific as possible.. my display is 50" so normal 100% dpi is way too small to be readable at a distance... so windows (10 and 11) default to 150%, text size is at 134... 
high dpi settings are not in effect on the exe's since that makes the windows smaller... if I were guessing it is because the font size is larger on my system, not everyone can read such tiny lettering as is in your screenshot..lol
