### ISSUE TITLE
high consumption of CPU LLE GPU

### ISSUE THREAD

**Issue by mkultimate** [Cxbx-Reloaded/Cxbx-Reloaded#1336] opened 2018-07-06 17:20 UTC
I understand that the function is experimental, but it helps to show some graphics in games like Burnout Revenge without that activated function shows black screen, but I noticed that activating the LLE function increases CPU consumption to such an extent that the computer slows down

ON LLE GPU FPS SLOW
![image](https://user-images.githubusercontent.com/16367065/42391720-f5e6cd7a-8115-11e8-83ab-a813e4c39f29.png)

OFF LLE GPU 60FPS stable
Note: the equipment works without any problem without any fall
![image](https://user-images.githubusercontent.com/16367065/42391985-d64c5998-8116-11e8-96ff-76276e62e6b2.png)

**Comment by RadWolfie** [comment] 2018-07-07 17:18
We are aware of the problem.
@LukeUsher had explained on discord:
> Exception handling on Windows are very slow. This is the reason why LLE is so slow in Cxbx-Reloaded.

We are currently using Windows' exception handler** to catch MMIO, hardware level, in LLE for read and write violation. In v1.0, or earlier, we will not be using Windows' exception handler and use a real CPU emulation instead.

** Even though we are catching any exceptions may occur to find any faults in our own code.

**Comment by mkultimate** [comment] 2018-07-08 16:08
thank you very much

**Comment by LukeUsher** [comment] 2018-07-23 13:04
Not a bug?

LLE in Cxbx-Reloaded is just this CPU intensive: There doesn't exist a computer that can handle LLE Cxbx-R in it's current form, so I'm closing this.

**Closed by LukeUsher** 2018-07-23 13:04 UTC
