### ISSUE TITLE
Sonic Hero's E3 Demo broken

### ISSUE THREAD

**Issue by BenNottelling** [Cxbx-Reloaded/Cxbx-Reloaded#426] opened 2017-05-03 01:24 UTC
Doesn't render anything before crashing
![capture](https://cloud.githubusercontent.com/assets/17304943/25645591/60c0c1d2-2f64-11e7-84cc-0c11225f25bc.PNG) Something I did notice though is after the first run I got a different error, only to be undone by deleting HLE cache
![capture](https://cloud.githubusercontent.com/assets/17304943/25645613/946e3f96-2f64-11e7-85ea-14e8ab4adc0c.PNG)

**Comment by PatrickvL** [comment] 2017-05-03 06:25
Yeah it might be HLE cache related

**Comment by BenNottelling** [comment] 2017-05-03 06:38
@PatrickvL maybe, but I feel like it worked a few days ago, I'll go back and test it on old commits to see what broke it sometime tomorrow and update the issue

**Comment by LukeUsher** [comment] 2017-05-03 06:42
Could you post a kernel log both before with a Nd without a hle cache present, and also the contents of the hle cache file located at %appdata%/Cxbx-Reloaded/HLECache.

**Comment by LukeUsher** [comment] 2017-05-03 07:14
I can't reproduce this: It boots for me no matter what the state of the HLE Cache:
![image](https://cloud.githubusercontent.com/assets/740003/25650992/70d244b4-2fd8-11e7-990c-6c2c3f46c04c.png)

As for the first error, that is to be expected, it's the same error we've always had, we just made the error dialogs more detailed.

**Comment by PatrickvL** [comment] 2017-05-04 06:58
This is a duplicate of #340

**Closed by PatrickvL** 2017-05-04 06:58 UTC
Labels: game-compatibility
