### ISSUE TITLE
quantum redshift

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/Cxbx-Reloaded#602] opened 2017-08-04 21:05 UTC
<img width="492" alt="latest q" src="https://user-images.githubusercontent.com/26704355/28986932-0c0a050a-7937-11e7-83a7-a7192d5572f4.PNG">

**Comment by literalmente-game** [comment] 2017-08-04 21:19
Please, post the logs of your test

**Comment by LukeUsher** [comment] 2017-08-04 21:25
Duplicate of #30

**Closed by LukeUsher** 2017-08-04 21:25 UTC
