### ISSUE TITLE
Castlevania Curse Of Darkness - white screen and noise and broken sound without any exeception codes

### ISSUE THREAD

**Issue by furrya** [Cxbx-Reloaded/Cxbx-Reloaded#272] opened 2017-03-25 06:34 UTC
![screenshot_2](https://cloud.githubusercontent.com/assets/25540784/24320055/47f8e40c-1170-11e7-8060-30868f436c51.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/869788/KrnlDebug.txt)

**Comment by blueshogun96** [comment] 2017-04-08 22:43
The reason this title causes so much trouble is because the vertex shader conversion is broken.  I had this problem when working on Cxbx before, and even managed to get it ingame, although I couldn't see anything being rendered.  Once the vertex shader conversion is fixed, then I can almost guarantee the game will be fully playable.

Shogun

**Comment by PatrickvL** [comment] 2017-04-08 23:02
Hey blue! Welcome to our little corner of the internet! Nice to see you're still interested in Xbox emulation!

**Comment by PatrickvL** [comment] 2017-04-08 23:03
And yes, vertex data and/or shader conversion is a real pain in the neck

**Comment by blueshogun96** [comment] 2017-04-08 23:40
Oh yes, it's great to be back.  IRL stuff takes my focus away from it most of the time, but I still like to come back and contribute from time to time if I can.  I spent my Friday night looking into what Luke managed to fix while I've been away, and I'm quite impressed that he managed to fix issues with Sega titles that I never did find fixes for.  Makes me want to get IDA up and running with all my old flirt signatures and maybe help with a few missing functions at least.

Shogun.

**Comment by furrya** [comment] 2017-04-10 01:20
With the 7760a7d (Apr 9 2017) build of Cxbx Reloaded, the game crashes at the start 
![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/24842780/0eedfab2-1dd7-11e7-829c-54f573c568ff.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/25540784/24842781/0eee1a7e-1dd7-11e7-8d57-82260de76587.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/908731/KrnlDebug.txt)
Seems like  #298 issue

**Comment by jarupxx** [comment] 2017-04-10 09:34
This regression will be fixed in PR https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/347

**Comment by furrya** [comment] 2017-04-10 10:30
@jarupxx Thanks!. This issue has  fixed now . The build of the emulator Cxbx-Reloaded Version 17fedee8fd41cfd21108a8fd0563168aa51101e9 (Apr 10 2017)  ![screenshot_3](https://cloud.githubusercontent.com/assets/25540784/24857525/9b75680c-1e23-11e7-97dc-1e0749c8014c.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/909735/KrnlDebug.txt)

**Comment by PatrickvL** [comment] 2017-08-21 15:28
This issue was moved to Cxbx-Reloaded/game-compatibility#173

**Closed by PatrickvL** 2017-08-21 15:28 UTC
Labels: game-compatibility
