### ISSUE TITLE
 Add support to handle / import Xbox Pro Action Replay Save game files

### ISSUE THREAD

**Issue by ElektroStudios** [Cxbx-Reloaded/Cxbx-Reloaded#1951] opened 2020-08-26 14:36 UTC
## Quick summary
CXBX does not seem to have support for **Xbox Pro Action Replay** Save game files neither for **Gameshark** save games.

## Details
It seems there is no way to handle the usage of these kind of save games to apply them on the HDD partition.

It would be very cool to let us import a **Xbox Pro Action Replay** save game in a guided, fashion way from the **CXBX** user-interface.

Save game's file format support is a very important part that shouldn't be forget when completing / developing a console emulator.
(I say this from my total humility, with the most absolute inexperience in the development of emulators, but as a veteran user of many emulators)

Please just consider to approve this suggestion / feature request to add support to handle these save games in the future.

### System Configuration:
Irrelevant.

### Additional Information (if any):
These kind of save games can be easy found on [gamefaqs](https://gamefaqs.gamespot.com/) website to test them. An example for **Halo** game:

https://gamefaqs.gamespot.com/xbox/472132-halo-combat-evolved/saves

**Comment by RadWolfie** [comment] 2020-08-26 20:57
@ElektroStudios See Luke's replied from previous closed ticket from [this link](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1893#issuecomment-625710739). There is a way, except it has some requirement in order to work properly depending on how titles save their games.

I don't think we will provide a import game saves UI from Cxbx-Reloaded. Any file explorer will be sufficient enough.

I'm not sure if we can provide ability to open where data storage is set to directly. Due to we don't have a cross-platform nor standard library to open a folder outside of Cxbx-Reloaded's GUI at this time.

**Comment by ElektroStudios** [comment] 2020-08-26 21:06
@RadWolfie 

Thanks for support!

If I understood correctly, any **Xbox Pro Action Replay** save game downloaded from gamefaqs website will not be enough to use / transfer that save with CXBX, because I would require something like a hash key of an XBox console in order to be able transfer the save?.

Is that right?. Not sure if what I would need is the disc hash key of the game, or a hash key of the console.

And in case that I don't own anymore an XBox console (so I can't dump any key) and I only have the game disc, there is not any legal way to accomplish this task?.

**Comment by LukeUsher** [comment] 2020-08-26 21:18
Importing save data from a real Xbox (regardless of via action reply or otherwise) requires a copy of the Xbox certificate key. This key is the same on every single Xbox, it’s not console unique, however we cannot legally include it with the emulator. 

If you have the keys from an Xbox, this savedata will just work already, no special import function is required. 

Based on that I’m closing this issue: this functionality already works provided you provide the certificate key.

**Closed by LukeUsher** 2020-08-26 21:18 UTC

**Comment by RadWolfie** [comment] 2020-08-26 22:12
duplicate of #1893

Basically asking for the same concept.

**Comment by ElektroStudios** [comment] 2020-08-26 22:49
Just please let me link this very useful additional info I found that explains missing details for which I was very confused about:

[https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/467]()

All info from here, and there, and together with the info in https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1893 could serve to help people on further investigation and figure out how to achieve all this.

Thanks @RadWolfie and @LukeUsher
