### ISSUE TITLE
Log Filtering/Options

### ISSUE THREAD

**Issue by BiatuAutMiahn** [Cxbx-Reloaded/Cxbx-Reloaded#48] opened 2016-12-21 22:10 UTC
Having a submenu to disable/enable certain API Logs, or even macros like Info/Warning/Error/Fatal would be very useful. Another one which might be a pain and thus wouldn't blame ya if you didnt bother would be a duplicate entry counter. like:
`EmuWarn (0x8FC): EmuNV2A_PMC_Read32($00000044) // Unknown PMC Address = $00000000 (Repeated xTimes)`

**Comment by LukeUsher** [comment] 2016-12-21 22:42
The first option is definitely on the radar, the second most likely will not be,

**Comment by BiatuAutMiahn** [comment] 2016-12-22 16:02
I might suggest 2 more features on the logging:
- Option to place Kernel Log in XBE path.
- Command Line arg for Log path/Method (Console|File)

**Comment by PatrickvL** [comment] 2016-12-25 15:38
This is mostly a duplicate of issue #14

**Closed** 2017-01-01 22:35 UTC
Labels: duplicate
