### ISSUE TITLE
jet set radio failed vertex buffer

### ISSUE THREAD

**Issue by souljagirlanonymous** [Cxbx-Reloaded/Cxbx-Reloaded#2132] opened 2021-02-06 13:32 UTC
![Capture](https://user-images.githubusercontent.com/78648398/107119505-ef4f0280-687f-11eb-80a1-cf526187d153.PNG)
![Capture](https://user-images.githubusercontent.com/78648398/107119512-f2e28980-687f-11eb-9829-a92e44bd2fd5.JPG)

im not good at coding AT ALL but i wanted to see if anyone could help me fix this problem?
and also have the latest feb 2 2021 update but cxbx 2 2017

**Comment by souljagirlanonymous** [comment] 2021-02-06 13:36
please let me know if ive not included enough information thanks xx

**Comment by ergo720** [comment] 2021-02-06 14:32
Judging from the screenshot, it's very likely caused by the known AMD GPU problem, pressing F2 should fix it. Anyway, this is the wrong place to ask for help, we have a [discord server](https://discord.gg/26Xjx23) for that. Closing.

**Closed by ergo720** 2021-02-06 14:32 UTC
