### ISSUE TITLE
Can't see characters or menus.

### ISSUE THREAD

**Issue by Conzpiracy** [Cxbx-Reloaded/Cxbx-Reloaded#1832] opened 2020-02-15 21:11 UTC
![Cxbx-Reloaded 51d5759a (Feb  8 2020) _ Emulating SE-010 v1 01 (Jet Set Radio Future) 2_15_2020 2_06_58 PM](https://user-images.githubusercontent.com/61096030/74595257-9c3fc800-4ffc-11ea-98e9-ea90e1843555.png)

Don't really know how to show a log, but I can say the only hack I have active is the "Run xbox threads on all cores". For some reason it doesn't show my character or any NPC's.

All other settings are (default)

Ryzen 7 2700x
rx580 8GB

**Comment by RadWolfie** [comment] 2020-02-16 04:22
**Please read [the guidelines](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/develop/README.md) and the [FAQ](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Frequently-Asked-Questions-(FAQ)) before opening an issue.**
 
Remember, Cxbx-Reloaded's issue tracker is not the place to submit [Game Compatibility](https://github.com/Cxbx-Reloaded/game-compatibility/blob/master/README.md) reports or ask for support. You must use our forum on [Discord](https://discord.gg/26Xjx23) for that.
 
Your issue has been marked as **Invalid** and will be close within 3 days.

---
Since you are new with GitHub. Please use search bar to find the answer or use discord before create a general issue ticket.

duplicate of #1803

**Closed** 2020-02-23 16:49 UTC
Labels: duplicate, invalid
