### ISSUE TITLE
Feature Request : Checking a new update available

### ISSUE THREAD

**Issue by Mored4u** [Cxbx-Reloaded/Cxbx-Reloaded#2392] opened 2022-08-20 17:58 UTC
## Quick summary

Add new feature to check the current version , then give the user the opition to upgrade to new version. 

## Details

By click >> **Help tap**  >> **check new version**  , also if possible appear changelog belong to new version , see the below picture.

![image](https://user-images.githubusercontent.com/5413459/185760047-8876946c-88e2-4f61-abf9-141622408e86.png)

### System Configuration:

* OS: Microsoft Windows 10/11
* CPU: Intel i7-9750h
* GPU: NVIDIA RTX 2080
* etc.

**Comment by ergo720** [comment] 2022-08-21 07:54
Duplicate of https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1038. We never have done change-logs, so that's likely not possible for the foreseeable future either.

**Closed by ergo720** 2022-08-21 07:54 UTC
