### ISSUE TITLE
Bug in DirectInput Controller mapping

### ISSUE THREAD

**Issue by niko1point0** [Cxbx-Reloaded/Cxbx-Reloaded#1432] opened 2018-09-06 00:03 UTC
When I use a PS4 controller, I click a button on the screen, such as the X, Y, A, B, buttons, and they get immediately mapped to my joysticks. Even when I do not touch my joysticks, they get mapped to the buttons. My prediction is that the joysticks are not 100% perfectly centered, and therefore the emulator picks it up as input.

Can you change DirectInput to detect stick input, only if the sticks have been moved significantly?

**Comment by RadWolfie** [comment] 2018-09-06 03:04
duplicate of #1207

**Closed** 2018-09-07 07:03 UTC
