### ISSUE TITLE
A title is currnetly being emulated. (Windows PopUp Error) 

### ISSUE THREAD

**Issue by EtchJackson** [Cxbx-Reloaded/Cxbx-Reloaded#1324] opened 2018-06-29 15:45 UTC
![image](https://user-images.githubusercontent.com/40697835/42101520-31a92372-7bbb-11e8-852b-cb2f29d8f489.png)

After loading the 4920 Dashboard into the Partition 2 Folder I pressed Load Dashboard as instructed and when I go to start emulation (normally and in debug) I am greeted with an error message. (As shown above)

Bear in mind I only have the 4920 Dashboard and nothing else changed to Cxbx Reloaded. Some tips would be much apricated. Thanks in advance!!!

**Comment by RadWolfie** [comment] 2018-06-29 15:56
I am unable to reproduce the issue.

Please close all opened Cxbx-R and verify every cxbx.exe are not listed in task manager. Then try again.

**Comment by EtchJackson** [comment] 2018-06-29 16:04
Well it worked!! Thank you! But now I'm getting an Xbox Error Screen.

![image](https://user-images.githubusercontent.com/40697835/42102616-5a346646-7bbe-11e8-92ab-5a783a454bdc.png)

Are the Dashboard and BIOS two different files?

**Comment by RadWolfie** [comment] 2018-06-29 16:18
Either your dashboard dump is corrupted/missing files or is not launch from Partition 2 directory from appdata (or user's preference to store data).

Yes, Cxbx-Reloaded doesn't require MCPX and BIOS ROM files. It will be provide as option later on.

**Comment by ergo720** [comment] 2018-07-01 08:47
The original problem is solved and the other is probably caused by what @RadWolfie said, so I'm closing this for now. If this is not the case, feel free to reopen this.

**Closed by ergo720** 2018-07-01 08:47 UTC
