### ISSUE TITLE
Futurama regression

### ISSUE THREAD

**Issue by jarupxx** [Cxbx-Reloaded/Cxbx-Reloaded#212] opened 2017-03-04 08:16 UTC
Futurama crashes in latest build, also 67c37feebd014a9e2725409f162e327bc24b0d8f, but in version 231e924bd13ae31a77a14b1f8128541a562ebaaa showed reach in-menu. In very older versions, reached in-game.

What is the reason for the crash in latest build? I do not know.
but I know the reason for not reached in-game in this version 231e924bd13ae31a77a14b1f8128541a562ebaaa. Because false detection 5344 version of the SetMinDistance function. False detection is resolved at #208.

**Comment by PatrickvL** [comment] 2017-03-12 00:18
Issue #223 might fix this regression

**Comment by LukeUsher** [comment] 2017-03-13 22:00
Something is very broken (Futurama PAL Version)

![image](https://cloud.githubusercontent.com/assets/740003/23877036/429811ae-0838-11e7-942f-6691a8050c63.png)

**Comment by bhodg22** [comment] 2017-03-29 02:38
![untitled](https://cloud.githubusercontent.com/assets/5080749/24436057/88e3f2c2-147c-11e7-8600-b799ed34928f.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/877633/KrnlDebug.txt)
Tried a slightly older build from march 23 with same results

**Comment by PatrickvL** [comment] 2017-03-30 13:50
Can you re-test this with build https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/6e250dc345f0c538238070ebf9b933dba348a114 or later?

**Comment by bhodg22** [comment] 2017-03-30 23:13
![untitled](https://cloud.githubusercontent.com/assets/5080749/24529963/39ac1b72-15f2-11e7-9abf-2c9890cb72ef.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/884033/KrnlDebug.txt)

**Comment by PatrickvL** [comment] 2017-03-31 04:31
Bummer. I'd hoped it had improved. Thanks for testing anyway!

**Comment by LukeUsher** [comment] 2017-03-31 20:18
I managed to get to Menus in the latest build 5bc6f53.

We never used to have Graphics probably in Futurama in the past, though, so it's a little strange

![image](https://cloud.githubusercontent.com/assets/740003/24567876/72b76240-1657-11e7-8cf1-442bbd24df2b.png)

**Comment by bhodg22** [comment] 2017-03-31 22:26
![untitled](https://cloud.githubusercontent.com/assets/5080749/24571493/e4943de0-16b4-11e7-97c8-7637568dc8d4.png)

**Comment by furrya** [comment] 2017-04-01 00:23
Same behavour on the latest build
![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/24573311/ac77bdee-16bc-11e7-88ee-be04188f8295.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/887197/KrnlDebug.txt)

**Comment by ObiKKa** [comment] 2017-04-09 21:39
This game has yet to reach that level of (nearly good) quality of emulation in an obsolete build of CXBX (Original version) seen in this Oct, 2011 video:
https://www.youtube.com/watch?v=qjiLaY1JT34

**Comment by furrya** [comment] 2017-04-15 01:24
Cxbx-Reloaded Version 98b86c8a (Apr 14 2017)
_____________________________________________________________

Futurama reaches the menu
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/923205/KrnlDebug.txt)
s now ;)

![screenshot_3](https://cloud.githubusercontent.com/assets/25540784/25059662/a34ae62e-21c5-11e7-85f6-32e755d9a53c.png)
![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/25059660/a349d176-21c5-11e7-8883-54c0f1e2d6ab.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/25540784/25059661/a34aaf24-21c5-11e7-8920-794873ac4669.png)

**Comment by bhodg22** [comment] 2017-04-15 03:07
Seems to be some inconsistencies 

![fut](https://cloud.githubusercontent.com/assets/5080749/25060269/7c011554-21dc-11e7-9fce-8afeb292760a.png)

**Comment by LukeUsher** [comment] 2017-04-15 07:13
Could be that your using a different version of Futurama. The PAL and NTSC versions differ.

**Comment by bhodg22** [comment] 2017-04-15 09:24
I am using PAL version

**Comment by jarupxx** [comment] 2017-04-15 11:17
Cxbx-Reloaded Version 98b86c8
Often crash intros too. Same as bhodg22.
If it crashes, EmuX86 warning will appear in Line 67000 of the debug log.
```
[0x15AC] EmuWarn: EmuX86_Write32Aligned(0x3F7D28B0, 0xBE18115A) [Unknown address]
[0x15AC] EmuWarn: EmuX86_Write32(0xBE18115E, 0x3F7D28B0) [Unaligned unimplemented]
[0x15AC] EmuWarn: EmuX86_Write32Aligned(0x3F768790, 0xBE89F2A9) [Unknown address]
[0x15AC] EmuWarn: EmuX86_Write32(0xBE89F2AD, 0x3F768790) [Unaligned unimplemented]
```
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/923539/KrnlDebug.txt)

**Comment by bhodg22** [comment] 2017-04-15 11:56
Are you also using the PAL version?

**Comment by jarupxx** [comment] 2017-04-15 12:07
Yes. I am using the PAL version.

**Comment by PatrickvL** [comment] 2017-04-15 12:17
X86 log messages are often an indicator that there's an unpatched function directly accessing hardware registers. However, in this case the addresses don't seem to map to a known hardware device, so there must be something else at play here. Debugging the caller functions can give us some insight

**Comment by CakeLancelot** [comment] 2017-09-18 15:35
I've transferred some info and also added a link back to this post for further information. This issue *should* be able to be closed now.

**Comment by PatrickvL** [comment] 2018-01-06 09:58
Closing this issues, as most relevant information is moved to https://github.com/Cxbx-Reloaded/game-compatibility/issues/71

**Closed** 2018-01-06 09:58 UTC
Labels: game-compatibility, regression
