### ISSUE TITLE
Error "Failed to open xbe file" on first launch

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [Cxbx-Reloaded/Cxbx-Reloaded#803] opened 2017-11-20 18:59 UTC
If AppData folder\Cxbx-Reloaded does not exist(for example you just got and run cxbx-reloaded first time) you will get error Failed to open xbe file. Next time it will be works as should until you clean AppData\Cxbx-reloaded folder again.

**Comment by BiatuAutMiahn** [comment] 2017-11-20 19:02
post log?

**Comment by PatrickvL** [comment] 2017-11-20 19:09
This issue is an intermediate situation after a fix done for Windows 7 in this pull request : https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/802

Before that, master from 18 November couldn't load xbe's at all. This is a regression since pull request #801 was merged in

**Comment by LukeUsher** [comment] 2017-11-22 14:44
Turns out this is an issue that has always existed, it just didn't manifest until now: It turned out that the EmuDisk folder was NEVER created, it was just assumed to be there. Now that .bin files are created alongside folder paths, the issue started to show up. Easy fix, pull-request incoming

**Closed** 2017-11-22 15:18 UTC
Labels: bug, file-system, kernel, regression
