### ISSUE TITLE
Flickering graphics in certain titles

### ISSUE THREAD

**Issue by Voxel9** [Cxbx-Reloaded/Cxbx-Reloaded#1266] opened 2018-06-08 15:38 UTC
As per @PatrickvL request, this issue has been created to discuss titles currently suffering from flickering/corrupted graphics:

(comment from PR #1246)
```
I suspect the flickering graphics are caused by a non-FVF vertex shader
being active during push-buffer rendering.
```
One example of a title presenting such issues is Leisure Suit Larry: MCL - when in-game, the rendered meshes completely flicker endlessly.

![image](https://user-images.githubusercontent.com/16278868/41115432-5e4e1dc6-6a7f-11e8-8e29-40bf0b5aa385.png)

If anybody else finds any more titles presenting such flickering and corruption, please post here so we can compile a list of test cases to work with.

## Additional Cases: ##
# Crazy Taxi 3
* [MotoGP](https://github.com/Cxbx-Reloaded/game-compatibility/issues/537#issuecomment-397510426)
* [Pure Pinball](https://github.com/Cxbx-Reloaded/game-compatibility/issues/802#issuecomment-398722796)

**Comment by bhodg22** [comment] 2018-06-09 01:14
JSRF seems to also be affected, white flickering can appear at the top of the screen or cover all of it in certain scenarios
![image](https://user-images.githubusercontent.com/5080749/41186209-11f641e4-6bd6-11e8-9949-c47920bda237.png)

Rally Sport Challenge Demo also has flickering 
![image](https://user-images.githubusercontent.com/5080749/41186223-40c94412-6bd6-11e8-96c0-16c04e2a11ad.png)

**Comment by PatrickvL** [comment] 2018-06-09 04:14
@bhodg22 Thanks for trying, but the cases you show are not the same type of issue : all vertexes seem to be transformed correctly (all I can see is they're colourized to heavily or lack textures).

This issue is about complete garbage after vertex transformation (likely caused by an incorrect vertex attribute your conversion, or wrong stride).

**Comment by Voxel9** [comment] 2018-06-09 11:12
I found another test case yesterday, but didn't have time to post. The Water sample from 5XXX has some flickering UI text, which can be clearly seen when looking upwards at least.
(Mega offtopic: As you can also see, the skybox textures in this sample are positioned very wrong too)

https://i.imgur.com/hlvOaJr.mp4

**Comment by PatrickvL** [comment] 2018-06-09 12:11
4627 is alright though?

**Comment by RadWolfie** [comment] 2018-06-09 13:16
But File 5849 looks hooooot. 🔥 😎
😉

I wonder if the sample's source code has changed between 4627 and 5849? If nothing really has changed since then. It's possible current code base could be missing include support to revised API or Symbol relative missing a patch or is broken.

**Comment by PatrickvL** [comment] 2018-06-10 09:06
Another possibility is vertex stream strides are not aligned correctly. At least in push buffer based drawing, vertex stride must be dword-aligned, especially when there's an odd number of shorts present.

**Comment by ObiKKa** [comment] 2018-06-13 11:42
Caught sight of this title bumping into that non-FVF vertex shader problem. I have seen plenty of other examples before but it's be hard to find them all.
- [Superman Returns: The Videogame](https://github.com/Cxbx-Reloaded/game-compatibility/issues/811)

**Comment by Stevoisiak** [comment] 2021-09-01 01:20
Confirming the issue in Jet Set Radio Future on an Nvidia GTX 1070 on Windows 10.

**Comment by ergo720** [comment] 2021-09-01 08:37
Closing and locking this issue, since it just says that a bunch of games have flickering graphics, which is too vague because that can have different causes.

**Closed by ergo720** 2021-09-01 08:37 UTC
Labels: graphics, informational
