### ISSUE TITLE
Vertex Declarations fail to compile in some titles

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [Cxbx-Reloaded/Cxbx-Reloaded#1381] opened 2018-08-11 07:39 UTC
PR #1377 brings regression in Prince of Persia: The Sands of Time US-029 1.42753 -  "Failed to create Vertex Declaration" just after boot.
[PopSoT_trace1376.zip](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/2280008/PopSoT_trace1376.zip)
[PopSoT_trace1377.zip](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/2280009/PopSoT_trace1377.zip)

Title list (update it if necessary):

- Cel Damage (failed for `X_D3DVSD_TOKEN_STREAMDATA`)
- Legends of Wrestling 2 AC-015 1.01
- Patch (XDK5849 Sample) FFFF0035 1.1048576 (failed for `X_D3DVSD_TOKEN_TESSELLATOR`)
- Prince of Persia: The Sands of Time US-029 1.42753
- Spikeout Battle Street

**Comment by LukeUsher** [comment] 2018-08-11 08:01
Not a regression: The same error occurs in both logs, however, 1376 (incorrectly) attempts to continue where 1377 exists: This is because these errors can cause crashes, and don't get noticed if they are silently ignored! We need to know about these errors, and they WILL cause crashes with later draw-calls when the failed vertex shader is used.

Thanks for telling us about this: It IS a problem, not not a regression, it's not a new problem, it's always been an issue.

For those who need it: The error is because we don't properly convert the vertex declartion:
```
DWORD dwVSHDecl[] =
{
	D3DVSD_STREAM(0),
	D3DVSD_CONST(0, 1),
	D3DVSD_NOP(),
	D3DVSD_STREAM_TESS(),
	D3DVSD_STREAM_TESS(),
		D3DVSD_REG(0, Unknown data type for D3DVSD_REG: 0x00
),
		D3DVSD_REG(0, D3DVSDT_FLOAT3),
		D3DVSD_REG(2, D3DVSDT_FLOAT3),
		D3DVSD_REG(3, D3DVSDT_D3DCOLOR),
		D3DVSD_REG(9, D3DVSDT_FLOAT2),
	// NeedPatching: 0
	D3DVSD_END()
};
```

**Comment by CakeLancelot** [comment] 2018-08-15 08:16
Cel Damage encounters this issue, as well as a few other games. I'll follow up with more details once I record logs, etc.

**Comment by TheArcadeStriker** [comment] 2018-08-15 12:48
Spikeout Battle Street now boots to SEGA/ADX/Dolby splash screens before staying in black, but shows Failed to create Vertex Declaration at boot.

**Comment by RadWolfie** [comment] 2018-08-24 06:00
Not all listed are resolved, reopening issue.

**Comment by PatrickvL** [comment] 2018-08-24 06:15
Thanks @RadWolfie, do you know which titles still go haywire?

**Comment by PatrickvL** [comment] 2018-08-24 13:45
https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/1408#issuecomment-415754805 shows MS-12 v1.02 (Kakuto Kajinn)

**Comment by revel8n** [comment] 2018-08-24 14:01
Sorry about that, forgot mentioning the fix number would close it automatically when merged.  Meant to only reference it so that it was known to be related.

The Patch sample is related to the default UsageIndex being 0 for tesselation streams, but since it has both a position and normal, conflicts with the vertex position which is also UsageIndex 0.  Defaulting the UsageIndex to 1 for them works, but may also possibly need to start a separate stream so they do not conflict.

i do not have the other games to test with unfortunately, but will see what i can find out through more testing.

**Comment by GTTeancum** [comment] 2019-09-11 13:17
Adding X-Men: Next Dimension as a title. Does not work as of Sept 10 2019 build. 

Also thanks to everyone for all they do to get these games running.

**Comment by GTTeancum** [comment] 2019-10-17 22:07
> 
> 
> Adding X-Men: Next Dimension as a title. Does not work as of Sept 10 2019 build.
> 
> Also thanks to everyone for all they do to get these games running.

Can confirm this is fixed for X-Men: Next Dimension. Thanks much!

**Comment by ergo720** [comment] 2021-09-05 08:54
Now that we have [HLSL vertex shaders](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/1801), is this issue still relevant today?

**Comment by PatrickvL** [comment] 2021-09-05 09:06
This one needs verification and clarification if there issue still persists

**Comment by CakeLancelot** [comment] 2021-09-05 18:43
Cel Damage is resolved now - don't have any other titles to test unfortunately.

**Comment by literalmente-game** [comment] 2021-09-07 22:02
All of the mentioned titles are fixed

**Comment by PatrickvL** [comment] 2021-09-08 06:56
Thanks for testing! Closed.

**Closed** 2021-09-08 06:55 UTC
