### ISSUE TITLE
[PAL] Jet Set Radio Future CD is damaged

### ISSUE THREAD

**Issue by Sakimotor** [Cxbx-Reloaded/Cxbx-Reloaded#466] opened 2017-05-14 22:32 UTC
Apparently the version that I have is damaged. Is it related to the files ? + the game crashes if I boot it a second time now. Using Windows 10 64-bit
 
![jsrf](https://cloud.githubusercontent.com/assets/20578016/26038288/75bbd78e-3905-11e7-9bb6-e29be7ae10f8.png)

![crash](https://cloud.githubusercontent.com/assets/20578016/26038314/fb26d1ee-3905-11e7-9c4e-bfd4258c66a7.png)

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/999775/KrnlDebug.txt)

**Comment by CakeLancelot** [comment] 2017-05-15 04:03
I had similar results with vsync off. Try clearing the HLE cache then try again with vsync on?

**Comment by Sakimotor** [comment] 2017-05-15 16:40
I've still got the CD problem but at least the game doesn't crash.

**Comment by literalmente-game** [comment] 2017-06-01 00:09
I've made some tests, and now I'm able to confirm: the "CD is damaged" was not a problem in the emulator, but in the way files are extracted from the ISO. When using something like MagicISO, the files will be extracted with no errors, but not all the files and somehow some files will be seem as "corrupt" when CxBx-Reloaded is loading them. To solve this, I've found a tool called "C-Xbox Tool" (Google for it, it's the first result). @Sakimotor, extract your ISO with the tool I've suggested and try to load the game again

**Comment by PatrickvL** [comment] 2017-06-01 07:22
@literalmente-game Thanks for your research, if this turns out to be the cause, this will need to be documented in the readme or wiki or whereever.

**Comment by Sakimotor** [comment] 2017-06-28 08:57
Yep, I was using MagicISO. Thanks literal

**Comment by LukeUsher** [comment] 2017-06-28 09:03
It's on the roadmap to eventually support direct loading of XISO files. This is still quite some time away as it requires implementation of a virtual filesystem in the kernel.

Perhaps as an interim measure we should implement functionality for extracting an XISO image to avoid issues like this in the future.

**Comment by LukeUsher** [comment] 2017-07-10 10:16
Closing this issue was it was just the result of not extracting the games files correctly

**Closed by LukeUsher** 2017-07-10 10:16 UTC

**Comment by HyperScorpio** [comment] 2017-08-07 22:45
Wow i use Qwix and it seems the problems belong to this tool. Thanks Literalmente! 👍

**Comment by HyperScorpio** [comment] 2017-08-08 11:32
The latest version of C-XBOX Tool is 2.0.7 search for c-xboxtool207.
Thank you all. 👍
