### ISSUE TITLE
Quantum Redshift reaches "reconnect the controller" error 

### ISSUE THREAD

**Issue by furrya** [Cxbx-Reloaded/Cxbx-Reloaded#280] opened 2017-03-26 02:18 UTC
![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/24327809/4a011c24-1215-11e7-8f86-7c6bcdca766d.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/870509/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/870510/Xbe.txt)

But the white screen with broken graphics in the latest build 
![screenshot_3](https://cloud.githubusercontent.com/assets/25540784/24327816/8544cae2-1215-11e7-852d-2d1fb0c32ef4.png)
Below the beginning of the KrnlDebug.txt because it about 13 mb
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/870512/KrnlDebug.txt)

**Comment by furrya** [comment] 2017-03-31 00:49
It's returned to the normal now with the latest commit
![screenshot_3](https://cloud.githubusercontent.com/assets/25540784/24531873/1fa7e2f6-15f7-11e7-81ce-1dd592c8affa.png)

**Comment by LukeUsher** [comment] 2017-03-31 09:02
I think this issue can be closed as it was about a regression. Quantum Redshift now experiences the same behavior as the initial issue #30 (which was about controller issues) so that one should be kept open

**Comment by PatrickvL** [comment] 2017-03-31 09:13
After the regression was fixed, this became a duplicate of #30. Closing

**Closed by PatrickvL** 2017-03-31 09:13 UTC
Labels: controller, game-compatibility
