### ISSUE TITLE
Config input crashes the emulator

### ISSUE THREAD

**Issue by CxbxUser** [Cxbx-Reloaded/Cxbx-Reloaded#2332] opened 2022-03-17 20:09 UTC
## Quick summary
trying to configure a device in a port crashes the emulator.

## Details
When I add a device into a port in config input then try press the "configure" button the emulator hangs for a bit then crashes, when I installed then reinstalled the program I was able to configure the device, but when I tried to close the config input window the emulator crashed again. 

### System Configuration:

* Windows 10
* Intel(R) Core(TM) I5 CPU 
* GTX 1050 (2 GB VRAM)
* 8 GB of RAM

### Additional Information (if any):
I only started using Cxbx Reloaded today.

**Comment by ergo720** [comment] 2022-03-17 20:15
Duplicate of https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/2293

**Closed by ergo720** 2022-03-17 20:15 UTC
