### ISSUE TITLE
Final Fight Streetwise - included Final Fight 1 wrong colours

### ISSUE THREAD

**Issue by dazchipsugar** [Cxbx-Reloaded/Cxbx-Reloaded#513] opened 2017-07-22 20:14 UTC
![image](https://user-images.githubusercontent.com/30376716/28494214-962626d2-6f1f-11e7-95fb-fe8639352c98.png)

![image](https://user-images.githubusercontent.com/30376716/28494221-b9401290-6f1f-11e7-8407-21c35ba12f6e.png)

![image](https://user-images.githubusercontent.com/30376716/28494234-0dd2a76e-6f20-11e7-8584-35e167d27919.png)

![image](https://user-images.githubusercontent.com/30376716/28494237-2850a03c-6f20-11e7-9202-d5a8624df8df.png)

![image](https://user-images.githubusercontent.com/30376716/28494242-4492f236-6f20-11e7-9aa3-6012b090c9ec.png)

[FinalF-Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1167605/FinalF-Xbe.txt)

I think it is due to how the FinalF.xbe executable (an official CPS1 emulator) is doing the 2d 90s equivalent of of some fading effect as it seems to fade from or to the correct colours whenever a new intro screen is started or ending, or a level is started of finished.

However it seems completely playable. I don't have the patience to go further given the amount of other emulators that will play the 90s game.

**Comment by LukeUsher** [comment] 2017-07-22 20:16
duplicate of #512

**Closed by LukeUsher** 2017-07-22 20:16 UTC
