### ISSUE TITLE
[GUI] Set Log files location and move folder equals hang or crash

### ISSUE THREAD

**Issue by Sarkie** [Cxbx-Reloaded/Cxbx-Reloaded#515] opened 2017-07-23 16:34 UTC
I set the location of the log file to a folder, I then moved the folder, Cxbx.exe would then hang or crash upon loading again.

Had to delete the keys:
HKEY_CURRENT_USER\Software\Cxbx-Reloaded

To get working again.

**Comment by ergo720** [comment] 2017-07-28 09:09
Cxbx doesn't crash/freeze if I set the keys KrnlDebugFilename and CxbxDebugFilename to an empty string after moving the folder. This code could fix this issue then?

In WndMain.cpp:127

```
if(RegCreateKeyEx(HKEY_CURRENT_USER, "Software\\Cxbx-Reloaded", 0, NULL, REG_OPTION_NON_VOLATILE, KEY_QUERY_VALUE | KEY_SET_VALUE, NULL, &hKey, &dwDisposition) == ERROR_SUCCESS)
```

And adding this in WndMain.cpp:149

```
dwType = REG_SZ; dwSize = 0;
if(PathFileExists((LPCSTR)m_CxbxDebugFilename == FALSE)
{
    RegSetValueEx(hKey, "CxbxDebugFilename", 0, dwType, NULL, dwSize);
}

dwType = REG_SZ; dwSize = 0;
if(PathFileExists((LPCSTR)m_KrnlDebugFilename == FALSE)
{
    RegSetValueEx(hKey, "KrnlDebugFilename", 0, dwType, NULL, dwSize);
}
```

**Comment by LukeUsher** [comment] 2017-07-28 09:11
Why not test and submit a PR ;)

**Comment by PatrickvL** [comment] 2017-07-28 09:14
@ergo720 What Luke said : Please submit a Pull Request for this, we'll be happy to test and merge (plus it will turn you into a contributor!)

**Comment by ergo720** [comment] 2017-07-28 09:25
I am sure it works, I have tested it in Visual Studio with a small test program and it correctly sets the key to an empty string. Alright, I'll submit a PR then

**Comment by ergo720** [comment] 2017-07-28 12:26
After more thought I realized the above code doesn't completely fix the issue. Check the PR for the new version

**Comment by ergo720** [comment] 2017-07-28 16:25
We cannot close this, cxbx now crashes if I try to set a debug folder location

**Comment by ergo720** [comment] 2017-07-29 19:00
Alright, I have changed my fix and built Cxbx in Visual Studio 2017 with it and this time it works. I'll submit a new PR

**Comment by ergo720** [comment] 2017-08-02 00:44
The problem is solved: from c5e4016 cxbx doesn't crash/freeze anymore after moving/renaming the debug folder. Sorry for not testing better the last time!

**Comment by Sarkie** [comment] 2017-08-14 08:50
If you set Debug Output on either and restart the application, the settings aren't saved or loaded properly now.

**Comment by PatrickvL** [comment] 2017-08-14 09:25
@ergo720 Could you take a look at the regression @Sarkie mentions above?

**Comment by ergo720** [comment] 2017-08-17 14:48
It seems that this error is rare: I was only able to reproduce it once but even then only the Xinput flag option had a garbage value, the other options were still all correct. I also tried to clear all the registry settings and download the latest version but the error still didn't occur...

**Comment by Sarkie** [comment] 2017-08-24 07:30
I will test again and take a video

**Comment by ergo720** [comment] 2017-09-21 09:39
@Sarkie were you able to reproduce this?

**Closed** 2017-10-08 11:24 UTC
Labels: enhancement, file-system, good-for-beginners, user interface
