### ISSUE TITLE
HLE Cache causes different error on second and later run 

### ISSUE THREAD

**Issue by BenNottelling** [Cxbx-Reloaded/Cxbx-Reloaded#427] opened 2017-05-03 01:34 UTC
Just something I noticed, I was testing Halo NTCS. The first picture is after clearing HLE Cache, second is without.
![capture](https://cloud.githubusercontent.com/assets/17304943/25645705/d67d52d6-2f65-11e7-8349-dce3a076b4f3.PNG)
![capture_2](https://cloud.githubusercontent.com/assets/17304943/25645708/d932f1d4-2f65-11e7-8023-dffdd3a94bed.PNG)

**Comment by PatrickvL** [comment] 2017-05-03 06:26
@LukeUsher Can you look into this perhaps?

**Comment by LukeUsher** [comment] 2017-05-03 07:18
Like with the Sonic Heroes E3 Demo, I'm getting the first behavior both with and without the HLE Cache, so I'm unable to reproduce this.

We would need to see your HLE Cache files as well as both your kernel logs to figure out what is going on.

**Comment by PatrickvL** [comment] 2017-05-03 07:29
@BenNottelling Could you clean your solution and do a rebuild - perhaps your builds are faulty (some of mine were too, so please give that a try)

**Comment by BenNottelling** [comment] 2017-05-03 07:35
@PatrickvL yes I'll do that, for now i have to sleep as is 12:30AM and I have to get up at 6:30, I'll report once I retest

**Comment by PatrickvL** [comment] 2017-05-03 07:43
So you're living in the U.S., west-coast? Or Canada? (Luke's British, I'm Dutch)

**Comment by BenNottelling** [comment] 2017-05-03 13:57
@PatrickvL US, northern Idaho to be specific. Although I don't quite know why this is important

**Comment by donwayo** [comment] 2017-05-03 14:08
Probably to get an idea of your timezone :)

**Comment by LukeUsher** [comment] 2017-06-20 20:21
@BenNottelling were you ever able to retest this?

**Comment by BenNottelling** [comment] 2017-06-20 23:27
@LukeUsher No, I never got around to it and have been distracted

**Comment by LukeUsher** [comment] 2017-07-10 10:18
Closing this as these issues don't seem to be cropping up anymore, and we have been waiting a long time for a response.

**Closed by LukeUsher** 2017-07-10 10:18 UTC
