### ISSUE TITLE
Using Exclusive Fullscreen causes "IDirect3D::CreateDevice failed" error

### ISSUE THREAD

**Issue by NicholasNRG** [Cxbx-Reloaded/Cxbx-Reloaded#1895] opened 2020-05-09 18:29 UTC
Games like Jet Set Radio Future or Panzer Dragoon Orta will boot unless Exclusive Fullscreen is enabled, causing the aforementioned error. Regular fullscreen (enabled with F10) stretches the image out, distorting the aspect ratio, and I would like to play my games at fullscreen with their original native resolution and aspect ratio...

**Comment by RadWolfie** [comment] 2020-05-09 18:53
We cannot fix xbox's resolution in exclusive fullscreen. Modern monitors do not support below 800x600. This has been frequency asked question and is pinned in discord server's help channel.

duplicate of #1542

---
**Please read [the guidelines](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/master/README.md) and the [FAQ](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Frequently-Asked-Questions-(FAQ)) before opening an issue.**
 
Remember, Cxbx-Reloaded's issue tracker is not the place to submit [Game Compatibility](https://github.com/Cxbx-Reloaded/game-compatibility/blob/master/README.md) reports or ask for support. You must use our forum on [Discord](https://discord.gg/26Xjx23) for that.
 
Your issue has been marked as **Invalid** and will be close.

**Closed** 2020-05-09 20:55 UTC
Labels: invalid
