### ISSUE TITLE
Quantum Redshift - Crash on title screen

### ISSUE THREAD

**Issue by jarupxx** [Cxbx-Reloaded/Cxbx-Reloaded#30] opened 2016-12-15 06:12 UTC
tested on 988e2fc5caae5a4b693d285e578fd2362c91e558
I follow the message that I pressed the start button, however nothing happens.

![quantum redshift](https://cloud.githubusercontent.com/assets/20138367/21213551/7f791df2-c2d8-11e6-8d8b-b9628d7bd926.jpg)

**Comment by LukeUsher** [comment] 2016-12-23 14:50
No idea what's going on here, my best guess would be one of the XAPI functions is not being correctly intercepted.

I don't have access to this game right now, but I'll have a look after Christmas, I think it's quite easy to find.

**Comment by PatrickvL** [comment] 2017-03-31 08:48
@jarupxx Is this a duplicate of issue #280?

**Comment by furrya** [comment] 2017-04-02 01:27
Now, it's passing away the controller error 
![screenshot_3](https://cloud.githubusercontent.com/assets/25540784/24583718/c04244ca-178e-11e7-937b-f077bd37c3c6.png)

**Comment by furrya** [comment] 2017-04-11 01:40
When hardware video mode is enabled strange error appears in this game
![5445](https://cloud.githubusercontent.com/assets/25540784/24888892/9c5f2ac2-1ea1-11e7-8c35-0595b8f2769b.jpg)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/911854/KrnlDebug.txt)

But, when I have run it's with harware video mode off, the game gets to the white screen now after the title
![title](https://cloud.githubusercontent.com/assets/25540784/24889125/349668e0-1ea3-11e7-8d20-785a56ed57de.jpg)
![45](https://cloud.githubusercontent.com/assets/25540784/24889028/9c54f966-1ea2-11e7-9f10-c178c8950d77.jpg)

Cxbx Reloaded 8dd3487232bac263d5e8a6b8edc1d97f01e396fb (Apr 11 2017)

**Comment by jarupxx** [comment] 2017-05-12 09:05
Tested on PR #458. The controller does work properly and reaches in-game. About the missing textures, I hope it helps investigation of @blueshogun96.
http://shogun3d-cxbx.blogspot.jp/2011/01/more-on-quantum-redshift.html

![ss1](https://cloud.githubusercontent.com/assets/20138367/25990791/fae22768-373b-11e7-813e-a4dfcfc75fe1.jpg)
![ss2](https://cloud.githubusercontent.com/assets/20138367/25990797/fe932a74-373b-11e7-8c08-cb7177b8d7a5.jpg)

**Comment by blueshogun96** [comment] 2017-05-12 18:54
Great work.  This is one of my favourite Xbox games, and I am greatly interested in it.  I read up on the fix for controller input issues and I'll give a few other titles a go that had the issue, such as metal slug 3.

Shogun

**Comment by jarupxx** [comment] 2017-05-13 00:54
Well, it became work controller by reconnecting. However, It is necessary to recognize the controller without reconnecting.

**Comment by PatrickvL** [comment] 2017-05-13 07:27
@LukeUsher Could you look into this?

**Comment by LukeUsher** [comment] 2017-05-13 08:29
Input shouldn't be a problem anymore after the latest merge, please report if there is a problem

**Comment by jarupxx** [comment] 2017-05-13 10:24
Tested with PR #460. Does not responded to input yet.
I reading the log, it seems that XInitDevices is called only for the function related to the input.
```
[0xD44] EmuXapi.cpp : EmuPatch_XInitDevices(
   dwPreallocTypeCount  : 2
   PreallocTypes        : 001A85B0
);
```
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/998519/KrnlDebug.txt)

**Comment by LukeUsher** [comment] 2017-05-13 10:36
Hmm. Perhaps XInitDevices is still incorrect.

**Comment by jarupxx** [comment] 2017-05-13 11:51
You might already be aware of this but I found information on XInitDevices.

> XBMC calls XInitDevices(0, NULL) which results in a default initialization. 
> MAME calls XInitDevices with a preallocated list of devices to look for. 
> http://coinopsproject.freeforums.org/trackballs-for-dummies-help-with-coinops-3-t94-20.html

Quantum Redshift not calls XInitDevices(0, NULL). It seems necessary to do "something" other than a default initialization.

**Comment by ObiKKa** [comment] 2017-05-13 20:55
Yes, same for me after PR 461 (Although this thing jaruppx referred to was based on a previous PR). Pressing on any key doesn't help to get the game past the first splash screen that I see, similar to some screens above. 
![2017-may-14_ splash-crash _01](https://cloud.githubusercontent.com/assets/18428108/26029182/5087fc06-3872-11e7-8c63-4b113f879ed4.png)

**Comment by jarupxx** [comment] 2017-05-15 22:44
Tested with PR #469. The controller is fully working now. Resolved by PR 460, 465, 469. Great work!

**Comment by PatrickvL** [comment] 2017-08-21 16:08
This issue was moved to Cxbx-Reloaded/game-compatibility#194

**Closed by PatrickvL** 2017-08-21 16:08 UTC
Labels: bug, controller, game-compatibility, regression
