### ISSUE TITLE
Stop Emulation hotkey does nothing intermittently

### ISSUE THREAD

**Issue by CakeLancelot** [Cxbx-Reloaded/Cxbx-Reloaded#590] opened 2017-08-03 23:40 UTC
According to the tooltip under the 'Emulation' dropdown, pressing F6 should stop the emulation. Though in the current build it seems this function doesn't work most of the time.
![2017-08-03_18-28-58](https://user-images.githubusercontent.com/5341136/28948231-fe74c924-7879-11e7-94ce-ee87363c6c43.png)
So far I haven't been able to reproduce what exactly causes this.. I closed some background programs which seemed to fix it but after reopening them the hotkey was still working somehow?

Quoting @PatrickvL from the Discord...
> F6 doesn't always work, might be related to window handles being corrupted. Create an issue for it too

**Comment by PatrickvL** [comment] 2017-08-27 11:21
Recently, a few missing break statements were added, who's absence might have caused this issue, so it'd be good to test this again with a recent build.

Unrelated to that, I've done some work on this in one of my work in progress branches; I'll try and look up the commits that concern this, so they can be cherry picked if so desired...

**Comment by ergo720** [comment] 2017-09-01 12:40
I think I have found a related error: I start a game with F5, it crashes and cxbx opens the crash window and I close it (with the mouse or enter), after that I cannot start the game with F5 anymore. Possible fixes I found are to start from the menu, reload the xbe or load a different one, close and reopen cxbx. F6 always worked in these cases.

**Comment by PatrickvL** [comment] 2017-09-05 08:08
My PR #713 attempts to fix the F6 not stopping emulation.

@ergo720 once that's in, could you re-test both that, and the issue with F5 after crash and report back on both here?

**Comment by ergo720** [comment] 2017-09-05 10:27
The problem is solved, but I did a test and strangely enough the issue is there in 5e45213bfe9a32552454d215045a3c75a15bde3a but gone in 9ff03f2259580bb4b4b7ba18aa1d96d6c6de3909. That means it wasn't #713 that solved it but #712 somehow did it.

**Comment by PatrickvL** [comment] 2017-09-05 11:01
I can't be sure, but vaguely remember F6 didn't always work with just #712, while #713 fixed those cases, so that's why I've submitted this fix on both sides. 

Anyway, thanks for testing @ergo720 but what about the [other crash you mentioned](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/590#issuecomment-326569807)?

**Comment by ergo720** [comment] 2017-09-05 11:11
The crash is unrelated to the F5 problem, it happens with any game that currently generates a crash window in cxbx for whatever reason

**Comment by PatrickvL** [comment] 2017-09-05 11:34
Okay @ergo720 please create a new issue for the unability to use F5 after a crash. I'll close this one.

**Closed by PatrickvL** 2017-09-05 11:34 UTC
Labels: bug, user interface

**Comment by ergo720** [comment] 2017-09-05 11:42
Sorry, I expressed myself not clearly, the problem I was having with F5 is solved by #712, I just don't know about F6 because that key always worked for me so I couldn't check it (the original issue of this post)
