### ISSUE TITLE
Invalid Pde in some circumstances

### ISSUE THREAD

**Issue by ghost** [Cxbx-Reloaded/Cxbx-Reloaded#1335] opened 2018-07-06 09:50 UTC
Some days ago, on Discord, I saw that it was reported that a game (not sure which) shows the following assertion ```assertion failed physicalmemory.cpp line:752 Expression: PointerPde->Hardware.Valid !=0```. This means that the pde which maps the queried pte is still invalid. That's an error, and should never happen, so this needs investigation

**Comment by ergo720** [comment] 2020-03-26 14:48
This is currently triggered only when the VMManager selects the chihiro memory layout (`m_MmLayoutChihiro` is true) and only with the latest merged commit of the loader branch (commit aad1af54257504adb693cff795db5e8ae4483410). Current develop branch (commit 1bc861ac52a57500a52aaf775220a7d181648290) is unaffected instead. Considering that this is an internal error of the VMManager and the loader only reserves memory but doesn’t change the internals of the manager, my guess is that commit b7de590fa06fffc9cb0122e9fdd4a0336abac1ed is the one that introduced this regression.

![vc3-PT-assert3](https://user-images.githubusercontent.com/45463469/77659817-d182f280-6f78-11ea-9d61-7f40b52ad807.PNG)

**Comment by ergo720** [comment] 2020-04-20 12:18
Turns out, it was actually caused by https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/1851 and it was fixed in https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/1866. Regarding the original problem in the first comment: since I have no idea which game was affected and no one has ever reported any issues with that assertion in two years, I'm going to close this for now. If someone does report this in the future, it can always be reopened.

**Closed by ergo720** 2020-04-20 12:18 UTC
Labels: bug, memory, needs-verification
