### ISSUE TITLE
Innocent Tears issues

### ISSUE THREAD

**Issue by furrya** [Cxbx-Reloaded/Cxbx-Reloaded#296] opened 2017-03-30 14:28 UTC
![screenshot_8](https://cloud.githubusercontent.com/assets/25540784/24509086/61e56eec-15a0-11e7-9280-fcc5dd16132d.png)
![screenshot_9](https://cloud.githubusercontent.com/assets/25540784/24509087/620e30f2-15a0-11e7-90e2-699e49f90f5b.png)
![screenshot_10](https://cloud.githubusercontent.com/assets/25540784/24509088/623443c8-15a0-11e7-8e03-2cdae04526a6.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/882716/KrnlDebug.txt)

**Comment by furrya** [comment] 2017-04-09 05:00
On the Cxbx-Reloaded Version 635dbcb5 (Apr  8 2017) appears KeBugCheck error. ever I press 'Yes' this error appears agan and again 
![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/24834845/441572a8-1d2b-11e7-95c2-b44c5fccfc95.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/907982/KrnlDebug.txt)

**Comment by PatrickvL** [comment] 2017-04-09 06:28
This log shows there are many unpatched functions hitting the nv2a

**Comment by LukeUsher** [comment] 2017-04-09 08:14
Yeah this title only got this far in the past because we ignored calls to KeBugCheck. To me, this screams bad idea as it only gets called when the game (or xdk code) decide that things are so broken the code cannot safely continue. If a Windows application called this function, it would instantly trigger a blue screen of death.

**Comment by jarupxx** [comment] 2017-04-14 07:30
On the PR #368  Recieved Breakpoint Exception has been fixed.
This game switches multiple. Xbe. KeBugCheck error dialog is displayed every time switching, but if I press Yes, play will continue.

![innocent tears1](https://cloud.githubusercontent.com/assets/20138367/25036381/758791e8-212e-11e7-8db2-630ca08879f9.png)
![innocent tears2](https://cloud.githubusercontent.com/assets/20138367/25036382/781ac6fa-212e-11e7-8b03-5f7c6e7edb74.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/921656/KrnlDebug.txt)

**Comment by PatrickvL** [comment] 2017-04-14 11:04
Amazing how far we've gotten!

**Comment by LukeUsher** [comment] 2017-04-14 11:24
Blueshogun should be pretty happy with this, I believe Innocent Tears is one of the titles he's interested in. 

We're getting there, slowly, but we're getting there!

**Comment by furrya** [comment] 2017-04-14 12:49
@jarupxx Great! The error has disapperead now and i can reach almost in-game but it's stucked with white screen after several screens , results of my trying are below

Cxbx-Reloaded Version 98b86c8a (Apr 14 2017)

![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/25043574/e6755b88-215b-11e7-94c4-20b5eba793d3.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/25540784/25043573/e6749bc6-215b-11e7-8d21-0cf822ea77cb.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/25540784/25043575/e677a7a8-215b-11e7-8e32-2e977b432fec.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/922059/KrnlDebug.txt)

**Comment by ObiKKa** [comment] 2017-04-14 15:36
A visual novel dialogue structure within this tactical RPG? Well, what would you know?! It looks like we don't know much about many of those Japan-only Xbox games.
I have an idea for the team, to Luke, Patrick or anybody else. What say that you can build in a screenshot capture function in the emulator's interface? It's so that anyone could make a shot of the title screen of a game for instance. In fact, no game database that has a profile of this page that I've checked even has the title screen!

**Comment by PatrickvL** [comment] 2017-04-14 16:05
Shameless plug : screen capture can be ported over from Dxbx ;)

**Comment by blueshogun96** [comment] 2017-04-14 19:33
Very impressive.  I'll have to update to the latest build later on and try it.  This title frustrated be way back when.

Shogun.

**Comment by ObiKKa** [comment] 2017-04-14 20:34
However for me this game keeps looping back to the long intro video all over again. I am unable to enter the menu first, let alone the game world.

**Comment by blueshogun96** [comment] 2017-04-16 18:01
+1 for a fan translation.  I own the game and play it on my debug Xbox on occasion but can't understand a word that's being said.  

Shogun

**Comment by furrya** [comment] 2017-04-17 00:58
@ObiKKa I have the same behaviour of emulation on Windows 7 , but when I tests it on Windows 10 I can reach in-game with V-sync enabled, although very long loading screens and battle scenes too fast

**Comment by blueshogun96** [comment] 2017-04-17 02:14
I wonder if games running too fast has to do with the fact that QueryPerformanceFrequency() is no longer returning the host PC values.

**Comment by ObiKKa** [comment] 2017-04-18 18:12
New issue. After PR #375 (Overlay conversion) & #376 (Integrated copy OOVPAs) I was never able to reach the character screen in I.T.. It often crashes after dialogue ends with a ginger-haired girl facing you. Once at the last round I saw a load screen as below so couldn't even see more dialogue and tute screens. I'm not sure what the problem is.

![collage-2017-04-19](https://cloud.githubusercontent.com/assets/18428108/25146157/3d0e6734-24b6-11e7-9ec9-786c5fd3928a.png)
[KrnlDebug_(2017-04-19_Crash-before-load-screen).txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/930644/KrnlDebug_.2017-04-19_Crash-before-load-screen.txt)

**Comment by PatrickvL** [comment] 2017-04-18 19:47
Ah, good news too, that's a relief ;)

**Comment by jarupxx** [comment] 2017-04-27 13:14
The default.xbe is as small as 60 kbyte and not include the D3D8 library.
We will be better to check the library before Fix up Render state and Texture States.
https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/master/src/CxbxKrnl/HLEIntercept.cpp#L133

[Xbe(default.xbe).txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/961634/Xbe.default.xbe.txt)

**Comment by LukeUsher** [comment] 2017-04-27 13:21
Good spot!
I'll fix it tonight

**Comment by PatrickvL** [comment] 2017-04-27 18:21
Just to verify: Does the absence of the D3D8 library mean that this specific (60kb small) xbe doesn't render anything? Is it some sort of launcher?

**Comment by blueshogun96** [comment] 2017-04-28 00:57
@PatrickvL yes sir, that is correct.  The default.xbe simply launches the appropriate .xbe as needed.  

Also, I tried to get ingame today, but I can't because the dpad still doesn't work.  So tbh, I don't know how you guys were able to get ingame.

Shogun

**Comment by ObiKKa** [comment] 2017-04-29 22:02
Just wanting to point out that after PR #406 (Index Buffer fixes) this game will crash instantly with an external error message.
Also, Buffy only shows an initial white screen (It kept getting worse with each major PR. But there should be a turnaround down the road.). Turok freezes after you load a save file (Might be the same when starting a brand new game) then crashes with an old error message (Lack of D3D:BlockOnTime implementation. It also says 'tell blueshogun'. LOL!).

![2017-04-30 _3rd-test_ index-buffer-fixes _01_crash](https://cloud.githubusercontent.com/assets/18428108/25559340/54d44370-2d7b-11e7-9e80-798344a34377.png)

**Comment by PatrickvL** [comment] 2017-04-29 22:07
Yeah, we're sorry that some changes cause regressions, but it's like growing pains: Once we through these phases, we'll function in a more mature way.

**Comment by PatrickvL** [comment] 2017-04-29 22:09
Rest assured we're very much aware of all the breakage, and truly want to fix these as soon as possible, it's just that we don't have much time, and it's only the three of us, currently.

**Comment by blueshogun96** [comment] 2017-04-29 22:11
lol I ran into that same error message when running Turok today.  Looks like some of my old error messages are still there!  

Anyway, there's a breakpoint in that function.  Uncomment it, and you'll find out what function is not getting caught.  Someone must have screwed up one of the signatures for a crucial function in that XDK version.

Shogun.

**Comment by PatrickvL** [comment] 2017-04-29 22:18
Not necessarily. If you mean the breakpoint in GetHostResource, that's not all too appropriate anymore, as we're working towards removing the abuse of the Lock field. Instead, we're adding associative maps, which will also detect the need for an update of resource conversions.

**Comment by LukeUsher** [comment] 2017-04-29 22:21
Re: deferred render state stuff: it's a minor bug with the HLE cache, it will be fixed very soon, it's a quick fix, it just needs to check for the presence of the D3D8 library before attempting to locate certain structures.

**Comment by RadWolfie** [comment] 2017-08-12 12:25
Hmmm... I'm not sure how long this title has been pretty much playable since it is able to multi-loading the .xbe files. Even starting from default.xbe, then it does the rest on its own normally.

P.S. This is from the latest commit in the master branch which was tested on 921cff1.

**Comment by PatrickvL** [comment] 2018-03-01 09:53
Closed due to its replacement here : https://github.com/Cxbx-Reloaded/game-compatibility/issues/683

**Closed** 2018-03-01 09:53 UTC
Labels: game-compatibility
