### ISSUE TITLE
Project Gotham Racing 2 (U)

### ISSUE THREAD

**Issue by Hamisxa** [Cxbx-Reloaded/Cxbx-Reloaded#2187] opened 2021-04-08 20:24 UTC
## Quick summary
Game boots into intro screen but crashes

## Details
Game boots into the intro screen and plays the video without issues, but when it starts loading the actual game menu it gets this error 
"Received Exception Code 0xC0000005 @ EIP := 0x00197435(=XNetGenEthernetLinkStatus +0x20a5)

### System Configuration:
* OS - WIndows 10
* CPU - Ryzen 5 3600X (no oc)
* GPU - RTX 2080 Super
* RAM - 32GB DDR4 @3200mhz
*EMU Version - FE84236

### Additional Information (if any):
N/A

**Comment by Masamune3210** [comment] 2021-04-08 23:25
this is not the place for stating if a game is working or not, unless i am reading the issue template wrong

**Comment by RadWolfie** [comment] 2021-04-09 00:23
**Please read [the guidelines](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/master/README.md) and the [FAQ](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Frequently-Asked-Questions-(FAQ)) before opening an issue.**
 
Remember, Cxbx-Reloaded's issue tracker is not the place to submit [Game Compatibility](https://github.com/Cxbx-Reloaded/game-compatibility/blob/master/README.md) reports or ask for support. You must use our forum on [Discord](https://discord.gg/26Xjx23) for that.
 
Your issue has been marked as **Invalid** and will be close.

**Comment by RadWolfie** [comment] 2021-04-09 00:23
duplicate of #2186

**Closed by RadWolfie** 2021-04-09 00:23 UTC
