### ISSUE TITLE
cx_x86 CMakeLists.txt causing trouble in generating vs .sln file.

### ISSUE THREAD

**Issue by jackchentwkh** [Cxbx-Reloaded/Cxbx-Reloaded#2251] opened 2021-06-25 07:18 UTC
## Quick summary

after clone cxbx-reloaded to local, trying to generate vs .sln files, it always failed unless I marked out the very last line of cs_x86\CMakeLists.txt

## Details

if I mark out the last line
install(TARGETS cs_x86 RUNTIME DESTINATION bin)
to 
#install(TARGETS cs_x86 RUNTIME DESTINATION bin)

then the sln file generation can be done. but then this introduce another issue, since cs_x86 belongs to import sub_module, every time when I want to commit a change, I have to restore CMakeLists.txt, then I can commit the change and push my branch.
but I can't keep the CMakeLists.txt in the restored state because the project won't compile. so whenever I want to commit a change, I have to restore CMakeLists.txt, after I commit the change, I have to edit CMakeLists.txt to mark out the last line again to make it compile. this really bothers me. 

### System Configuration:

* OS Win10 X64
* CPU Intel i7
* GPU Nvidia 1070
* etc.

**Comment by ergo720** [comment] 2021-06-25 11:30
I'm unable to reproduce this. I cloned the repository from scratch with `git clone --recurse-submodules https://github.com/Cxbx-Reloaded/Cxbx-Reloaded.git`. then I switched to the cxbxr directory, created a build folder and, from it, I ran `cmake .. -G "Visual Studio 16 2019" -A Win32`. The solution file was generated correctly. I also tried to build it with VS2019 and everything worked as expected.

**Comment by RadWolfie** [comment] 2021-06-25 15:29
@ergo720, the issue is from VS 2017's built-in CMake which will always remain at version 3.12. Version 3.13 of CMake has the fix for this type of issue.

**Comment by x1nixmzeng** [comment] 2021-07-01 21:02
Happy to approve a minimum supported cmake version number bump in the the cs_x86 repro if this avoids this issue with vs2017

**Comment by RadWolfie** [comment] 2022-02-16 04:17
Resolved in https://github.com/x1nixmzeng/cs_x86/pull/11 pull request and is currently upstream.

**Closed by RadWolfie** 2022-02-16 04:17 UTC
Labels: bug, cmake
