### ISSUE TITLE
Your development release for Mar 21 is triggering Windows Defender with a Trojan:Win32/Bearfoos.A!ml. I don't believe in false positives unless they're from Norton or McAfee, so good luck with that.

### ISSUE THREAD

**Issue by lcfur** [Cxbx-Reloaded/Cxbx-Reloaded#1571] opened 2019-03-24 18:19 UTC

**Comment by feikname** [comment] 2019-03-24 18:44
https://www.virustotal.com/gui/file/81a30d69dfbedecdac4e14d12591829f648b3e3e8e3fdd237436ab9fa8a28278/detection

No detected malware whatsoever from VirusTotal nor from my machine's Windows Defender using latest commit build artifact. Where did you download it?

**Comment by LukeUsher** [comment] 2019-03-24 18:48
The development builds are entirely automated and are compiled from our code repository every time new code is merged. There is no stage where it is possible for anybody to add malicious code that is not present in the main source code.

The change that was merged in that development build can be found here https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/1568/files, and as you can see, is a very minor change that cannot possibly be malicious.

I assure you that it is a false positive.

I also use Windows Defender on my machine and it does not detect this is a virus: this is also confirmed by running the development build through VirusTotal: (Results here, 0/60 engines detected anything malicious) https://www.virustotal.com/#/file/588cd15509eccfce2dde865c4a0384fe9476db905c9a7ef9be301b25843470a0/details

**Comment by BenNottelling** [comment] 2019-03-24 18:58
> I don't believe in false positives unless they're from Norton or McAfee

I knew apple fan boys were a problem.. but not windows defender. 
Anyways, I ran the last three builds through virus total.
`Yesterday march  23rd: `https://www.virustotal.com/#/file/23784014891438f21d3cca908dcc0d0ebc21420bfb3bd20f146225dc5dd1155d/detection
`March 20th: `https://www.virustotal.com/#/file/588cd15509eccfce2dde865c4a0384fe9476db905c9a7ef9be301b25843470a0/detection

`and finally, one week ago, march 17th: `https://www.virustotal.com/#/file/8440bcf604553514de765760688e2ac2c8edbaba9854bd9ea2efc60664681fd8/detection
That one isn't even from the date you mentioned nor is from the master branch which should have been what you downloaded anyways. You can see all of the changes here: https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/compare/cmake_loader_reloaded
I can tell you that both @RadWolfie and @PatrickvL have done a lot of work for this emulator and are trustworthy, none of their changes would be harmful. The changes by @GXTX are also completely safe and simply have the CI services use the new cmake build method.

**Comment by bobsaidwzob** [comment] 2019-03-24 21:26
I also had this happen to me today. The release from 3/20. I opened cxbx and all of a sudden the screen went black a few times and then half of the screen was black and half was my desktop. Couldn't close cxbx through the startbar or task manager since the window was blocked by the black half of my screen. Windows automatically deleted the exe and when I went to redownload the latest build, chrome detected it as a virus. Chrome won't even let me open the zip file.

**Comment by AzurikRiseOfPerathia** [comment] 2019-03-25 00:58
@bobsaidwzob 
Your computer may not be powerful enough. Or at least that viruses are in your computer, because having downloaded ALL BUILD for years no one asked me to worry about opening.

**Comment by bobsaidwzob** [comment] 2019-03-25 01:01
Possibly but I've never had an issue with anything else and the stable build works and runs fine and can download with no virus issues. It's just the most recent build that there's an issue. As far as the computer being not powerful enough it should be. I can run all other emulators just fine. i7 32gb ram Intel graphics.

**Comment by AzurikRiseOfPerathia** [comment] 2019-03-25 01:09
[https://www.virustotal.com/gui/file/23784014891438f21d3cca908dcc0d0ebc21420bfb3bd20f146225dc5dd1155d/detection](url)

I just launched it instantly. is everything looks clean. Do you have several Anti-Virus software that could conflict or not?

**Comment by bobsaidwzob** [comment] 2019-03-25 01:12
Just windows defender. That didn't even detect it. It's just chrome when it scans the file before unzipping it.

**Comment by AzurikRiseOfPerathia** [comment] 2019-03-25 01:15
Did you try another browser? Try Opera or Mozilla Firefox (the best I can do for you) To download the file.

If that works you must restore your Chrome,

**Comment by LukeUsher** [comment] 2019-03-26 09:02
Yeah we've had this a few times. it's a false positive.

If in doubt, run the archive through VirusTotal... and always make sure you download from this Github (link in readme) and *never* from untrusted websites.

**Closed by LukeUsher** 2019-03-26 09:02 UTC
