### ISSUE TITLE
HLSL: AMD GPU Regression

### ISSUE THREAD

**Issue by RinMaru** [Cxbx-Reloaded/Cxbx-Reloaded#1803] opened 2019-12-22 03:10 UTC
#1801 Has cause major bugs with AMD Hardware, Mostly BlackScreens

**Reported AMD GPUs**
- Radeon RX 580
- Radeon RX 570
- Radeon RX 560 (reported [here](https://github.com/Cxbx-Reloaded/game-compatibility/issues/954))
- Radeon RX 550
- Radeon RX 530
- Radeon RX 480
- Radeon RX Vega 56
- Radeon Pro Vega 20
- Radeon HD 7970
- Radeon HD 4200 (Vulkan not supported)
- Radeon R9 380X

**Reported Games**
- Vexx AC-005 v1.03/ Menu is rendered but 3D assets are all black
- Crash Tag Team Racing VU-065 v1.02/ 2D elements loaded but crashes at first loading screen
- Crash Wrath Of Cortex VU-003 v1.01/ Some 3D models fail to render
- Xbox Dashboard FFFE0000 v1.269657855/ 2D elements only rendered
- Jet Set Radio Future / Invisible NPCs/character and menu

**_NOTE_** Use [DXVK](https://github.com/doitsujin/dxvk) as a temporary workaround. Use the 32bit d3d9.dll.
The file path will be `dxvk-1.#.tar.gz\dxvk-1.#.tar\dxvk-1.#\x32\d3d9.dll`

**Comment by hinksta47** [comment] 2019-12-25 00:24
Hi @RinMaru, I can confirm that my AMD Radeon Pro Vega 20 (Apple MBP 2018 - running BootCamp obviously) also has the exact same issues.

**Comment by Earth271072** [comment] 2020-01-06 02:55
Can confirm I'm having issues with Jet Set Radio Future on my Radeon RX Vega 56

**Comment by SimonDenton** [comment] 2020-01-12 07:55
Can confirm with RX 580

**Comment by KuroRaiden** [comment] 2020-01-17 18:15
Graphical issues for JSRF and Ninja Gaiden Black.
**JSRF:**
- Invisible Characters
- Laggy main menu

**Ninja Gaiden Black**
- Strange texture errors 


Hardware:
GPU - Radeon RX 580 Series - Primary/Discrete
CPU - AMD Ryzen 5 2600 Six-Core Processor

**Comment by suchturista** [comment] 2020-02-24 21:45
Same thing happening for JSRF on my Radeon RX 570. No 3D models.

**Comment by DeathAdrift** [comment] 2020-03-10 17:40
JSRF on my Radeon RX 550. No 3D models.

**Comment by RadWolfie** [comment] 2020-03-20 21:48
Confirmed same issue with Radeon HD 4200 for:
* Xbox Dashboard has black background and visible 2D elements.
* Jet Set Radio Future's 3D models and menu are invisible.

Cannot test with dxvk wrapper due to older driver (before Vulkan existed).

**Comment by dascratch** [comment] 2020-03-24 02:57
Confirmed same issue with Radeon RX 570 4Gb / Ryzen 3600X
THPS2x:
Invisible Characters in menu.
Black background and visible 2D HUD elements in game.

So i put DXVK 32bit d3d9.dll in CXBX main. Then start exe and it's just show me an error 0xc0000005.

**Comment by ESPPIRAL** [comment] 2020-03-24 16:27
r9 380x can be added to the list.

**Comment by Shook1-cmyk** [comment] 2020-04-02 22:31
Where exactly do I put d3d9.dll to make this work? I'm super new to this.

**Comment by RinMaru** [comment] 2020-04-03 03:12
> Where exactly do I put d3d9.dll to make this work? I'm super new to this.

in the same folder as Cxbxr

**Comment by CakeLancelot** [comment] 2020-04-13 09:03
For those who have confirmed this issue with their GPU, please test the following PR and report if it fixed it: #1865.

**Comment by NNX3x** [comment] 2020-04-14 22:31
Using and RX580 I can now see graphics in a few titles I have that have worked prior, but hadn't worked in some time do to AMD DX9 blunder . A few games I can now see go in-game etc. for the first time.

**Comment by RinMaru** [comment] 2020-04-15 21:38
yep its fixed

**Comment by Damien5497** [comment] 2020-04-17 06:44
I can confirm with my RX 560 that the temporary switch to Shader Model 2.0 on AMD GPUs has fixed the dashboard issue #954, though I don't have any games at the moment.

**Comment by LukeUsher** [comment] 2020-04-20 08:12
Fixed as of #1865

**Closed by LukeUsher** 2020-04-20 08:12 UTC
Labels: graphics, regression

**Comment by Sophie-bear** [comment] 2020-07-08 16:38
Hey guys, just wanted to say because I think this is related to this issue (and it may have regressed again), I had unbearable lag in THPS2X on my Radeon VII until employing the workaround using DXVK mentioned in the original post here. There is still lag and model pop-in when things are changed in the environment occasionally, but the workaround results in a much more playable experience.

**Comment by RadWolfie** [comment] 2020-07-08 21:01
@Sophie-bear, your issue has nothing relative to the main topic issue on this ticket. Which are two things, invisible characters in certain condition and black screen. Whilst other graphic vendor are working fine as-is.

Since the ticket's issue has been resolved, this ticket is now lock.
