### ISSUE TITLE
Suggestion: Make a way to use ISOs / real discs

### ISSUE THREAD

**Issue by Simon-Brannstrom** [Cxbx-Reloaded/Cxbx-Reloaded#1830] opened 2020-02-13 23:50 UTC
I have an idea. Since XBE's are required to run a game from the emulator, how about making a built-in tool to extract the XBE's directly from ISO images of various xbox games or perhaps even actual discs.

Or how about running games directly from a disc or ISO?

**Comment by Margen67** [comment] 2020-02-13 23:51
Duplicate of #205.

**Closed** 2020-02-14 07:17 UTC
