### ISSUE TITLE
DSound's Stream Packet Lockup Issue

### ISSUE THREAD

**Issue by RadWolfie** [Cxbx-Reloaded/Cxbx-Reloaded#1727] opened 2019-09-12 15:51 UTC
Title says it all.

The affected titles are:
- Grand Theft Auto III **(confirmed)**
  - After garage checkpoint, audio kept looping which prevent first mission checkpoint to start.
- Grand Theft Auto Vice City **(confirmed)**
  - During mission intro then cause a lockup.
- Azurik - Rise of Perathia **(confirmed)**
  - At start of gameplay.
- ~~Project Gotham Racing 1 & 2 **(likely)**~~ Unrelative to stream's packet issue
  - After intros, become stuck at loading screen. Remove silence.wma file allow title to progress further.

**UPDATE:** Found out the source of cause. Stream's single packet buffer size is larger than the host's buffer size. This is the cause of lockup for same packet.

**Comment by LukeUsher** [comment] 2019-10-13 20:57
Marked as high priority, because it causes games to lock up.

**Comment by AzurikRiseOfPerathia** [comment] 2019-10-13 21:04
@RadWolfie I rectify the post of Red that does not happen only at the beginning, but every load of levels or movies.

**Comment by hinksta47** [comment] 2019-12-24 23:58
@RadWolfie I can confirm that PGR2 also suffers the same issue as PGR. I removed both instances of silence.wma and it boots to the menus.

**Comment by RadWolfie** [comment] 2019-12-25 03:28
@hinksta47 I need to re-verify PGR if it is packet issue or not. It's been a long time I debug the title.

Although, when the time come, I will start debug Grand Theft Auto 3 for two separate issues. Once both issues are resolve, I will personally retest Vice City and PGR to be sure the issue is 100% resolve.

**Comment by RadWolfie** [comment] 2019-12-27 18:03
I have discover the issue for packet lockup, the fix will take longer as internal packet management needs some rework.

**Closed** 2020-01-24 08:35 UTC
Labels: HLE, bug, high-priority, sound
