### ISSUE TITLE
Only intel gpu appears in video-settings even though it's a dual GPU system.. 

### ISSUE THREAD

**Issue by Exequiel3k** [Cxbx-Reloaded/Cxbx-Reloaded#1155] opened 2018-05-11 22:54 UTC
Hey all,
The Surface Book has a dual GPU (intel/NVIDIA), although only the Intel GPU appears in video-settings.
I tried forcing the app via Nvidia Control Panel without success. 
I just wanted to let you'll know.
Thanks for the hard work in bringing back to life our memories👍

**Comment by ergo720** [comment] 2018-05-12 09:28
I have a dual GPU system (Intel/NVIDIA) too and I'm able to select one or the other via the context menu option "Run with graphics processor". Also, wasn't this fixed in #784?

**Comment by Exequiel3k** [comment] 2018-05-12 13:28
For ref.. 
[https://ibb.co/mPtiFd](url)

**Comment by Exequiel3k** [comment] 2018-05-14 01:40
I booted today and it only displays the NVIDIA gpu, that’s great news..!😅

That said, I’m wondering why it doesn’t show both options since I’m pretty sure I’ll be stuck sometimes rebooting my pc until I see the right gpu appear..

**Comment by LukeUsher** [comment] 2018-05-15 10:00
Closing this as it's purely related to OS/Driver issues at this point.

Cxbx-Reloaded uses D3D9 via a wrapper & also exports the necessary symbols to trigger High performance mode on supported drivers.

There's nothing more we can do.

**Closed by LukeUsher** 2018-05-15 10:00 UTC

**Comment by Exequiel3k** [comment] 2018-07-05 20:52
I just want to point out this problem only occurs with this emulator.
I use a lot of emulators (dolphin, higan, m64p, pcsx2, pcsxr-gpxp, Cemu, ryujinx) and none of them have this issue.
If you think this is a driver issue, then so be it but its quite odd. 
Thanks for your time.

**Comment by LukeUsher** [comment] 2018-07-05 21:42
@Exequiel3k that's because all those other emulators use newer versions of DIrectX than 8.0 (or OpenGL). If the emulator used DirectX9, this wouldn't be a problem.

The issue is that DirectX8 has poor driver support on modern machines.
