### ISSUE TITLE
dino crisis

### ISSUE THREAD

**Issue by mystro1213** [Cxbx-Reloaded/Cxbx-Reloaded#779] opened 2017-10-28 05:10 UTC
game fps is over 30 goes to 200 did force vsync nothing changed
game texture is broken no environment only characters

**Comment by PatrickvL** [comment] 2017-10-28 05:42
Please report game specific findings in the Cxbx-Reloaded/game-compatibility issue tracker

**Comment by mystro1213** [comment] 2017-11-01 21:31
![bandicam 2017-11-01 23-26-05-220](https://user-images.githubusercontent.com/24327966/32298854-26efe09a-bf5c-11e7-986f-e35c0dd848de.jpg)

**Comment by CakeLancelot** [comment] 2017-11-01 21:35
As PatrickvL said, please report it in game-compatibility issues. In this case, there is already an issue for this game [here](https://github.com/Cxbx-Reloaded/game-compatibility/issues/114).

**Comment by RadWolfie** [comment] 2017-11-01 23:16
Duplicate of Cxbx-Reloaded/game-compatibility#114

Plus wrong place to report. Any game relative issues must be report in [Cxbx-Reloaded/game-compatibility](https://github.com/Cxbx-Reloaded/game-compatibility) repo.

**Closed** 2017-11-01 23:16 UTC
