### ISSUE TITLE
Cxbx-Reloaded cannot handle paths containing a $ character.

### ISSUE THREAD

**Issue by Sarkie** [Cxbx-Reloaded/Cxbx-Reloaded#475] opened 2017-05-20 21:39 UTC
I think it is having trouble creating the "$u" directory maybe?

If totally wrong, just close this issue.

Build: 20th of May, 2017
82c19073

Console:
[0x126C] EmuWarn: EmuKrnl: IoCreateFile Failed! (0xC000003A)

[0x126C] EmuWarn: EmuX86_Read32(0x5129F86A) [Unaligned unimplemented]
[0x126C] EmuWarn: EmuX86: 0x00124275: Not Implemented

[0x126C] EmuMain: Received Exception (Code := 0xC0000005)

 EIP := 0x0012427A(=XMountUtilityDrive+0x14588)
 EFL := 0x00010213
 EAX := 0x06C1F9D8 EBX := 0x0012424A ECX := 0x00000000 EDX := 0x06C1F96C
 ESI := 0x1445ED88 EDI := 0xFFFFFFFF ESP := 0x06C1F998 EBP := 0x06C1F9E8
 CR2 := 0x00000000

Issue:
![image](https://cloud.githubusercontent.com/assets/283203/26279479/265fd0d0-3dad-11e7-995b-0636e04c87cb.png)

**Comment by RadWolfie** [comment] 2017-05-21 02:20
I had discovered this issue before and investigated why contentmeta.xbx is very important. Turns out it is used for DLC contents. So, all games with DLC content are affected if attempt to use it. I think @LukeUsher can verify its location since he now has hardware debug kit. I think $u is actually meant as TitleID, I'm not sure... If it is, then $u shouldn't be there. It could be easily removed within _CxbxConvertFilePath function from EmuFile.cpp file.

This is one simple patch for it. Since I only see $u and $U so far with titles I had tested against it.

```
if (RelativePath.length() > 3 && RelativePath[0] == '$')
    RelativePath.erase(0, 3);
```

Another issue relative with CreateFile is Panzer Dragoon ORTA is trying to create files without attempt to create directory repeatedly throughout the game. As explained in #418.

**Comment by LukeUsher** [comment] 2017-05-21 06:18
I'll have an answer about both of these things today. Hopefully before 5:00PM GMT

**Comment by LukeUsher** [comment] 2017-05-21 13:37
Dollarsigns ($u, $c, etc) are allowed as characters in the FATX filesystem, but not in NTFS, so the folder name as $u is probably correct. 

I can confirm that $u is where patches/updated files from Xbox Live are kept. Titles that are able to be updated read from TitleData/$u/ before DVD-ROM, using any updated files if they are present.

We'll have to handle this in some other way, perhaps by replacing any `$` we encounter with a character that is compatible with NTFS file systems, perhaps `!` can be used.

**Comment by PatrickvL** [comment] 2017-05-21 13:56
The dollar character doesn't appear in this of illegal filesystem characters : https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#naming_conventions Do you have a link about this for NTFS specifically?

**Comment by PatrickvL** [comment] 2017-05-21 13:58
Often, an underscore is used as a replacement character. Or an escape sequence like in URL encoding can be applied, perhaps that's preferable as it can be used to fix any other illegal filename character we might encounter in the future

**Comment by LukeUsher** [comment] 2017-05-21 13:59
Oh good point, $ does work. This is a non-issue entirely then. I should've actually read the spec ;)
So the reason titles fail to access $u, is because, correctly, it doesn't exist because the title hasn't downloaded any updates from XBLA

This can probably be closed then!

**Comment by RadWolfie** [comment] 2017-05-21 18:11
Hmm, interesting finding. I swear $ didn't work for me when I did some files in the past. I had tried it out recently, is working fine. Pretty sure we can ignore $ sign issue for a file attempt to find. I think we need to filter certain error codes out as if it works as expected. Since it only did check once, not repeatly.

**Comment by PatrickvL** [comment] 2017-05-21 18:34
The dollar sign may still indicate some sort of path alias, so I wouldn't close this issue yet until we've discovered how the real kernel behaves in this regard.

**Comment by RadWolfie** [comment] 2017-05-22 01:27
This would be great to know, except XBLA network for original box is shutdown years ago. Other alternate is to check games that has DLCs disc or something alike (like Halo 2, since it does has expansion map pack).

**Comment by LukeUsher** [comment] 2017-05-22 05:19
If you have dlc or updates for titles backed up, you should be able to copy the files to the write location and titles can find it there. Having Cxbx-Reloaded Actually going online and downloading content​ would be piracy. And we do not, and will not support illegal activity

**Comment by LukeUsher** [comment] 2017-06-28 09:08
Closing this as it is a non-issue. The $ character is allowed in filenames & titles are looking for this folder to determine if an update is installed.

It is expected that querying this directory would fail when no updates are present, so this is in-fact, correct behavior.

**Closed by LukeUsher** 2017-06-28 09:08 UTC
