### ISSUE TITLE
"Received Exemption Code 0xC0000005 @ EIP :=0x00048228(=unknown+ 0x0)" on JSRF After Update

### ISSUE THREAD

**Issue by OlayColay** [Cxbx-Reloaded/Cxbx-Reloaded#470] opened 2017-05-15 23:58 UTC
<img width="516" alt="chrome_2017-05-15_19-50-45" src="https://cloud.githubusercontent.com/assets/28718703/26084164/185b7092-39a8-11e7-913b-94aee789f751.png">
I was playing JSRF fine with the May 13th build. When the May 14th build came out, I installed it. Now I get this error when I try JSRF. Did I install it incorrectly or something? I've already tried reinstalling JSRF
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1002809/Xbe.txt)

 
Specs:
Dell Inspiron 3847
Intel i3-4130 CPU 3.4 ghz
8gb ram
NVidia GeForce 750 TI OC
Windows 10 Home x64

**Comment by PatrickvL** [comment] 2017-05-16 05:05
It's unclear what caused this, but we're aware of the issue. Thanks for the heads up

**Comment by LukeUsher** [comment] 2017-05-16 05:57
It seems to be the re-patching of XGetDeviceChanges, which seems necessary for some titles to read input correctly

However, thinking about it, I believe unpatching XGetDeviceChanges is what made JSRF run in the first place...  so I'm not sure what to do here.

Roll back the re-patching of XGetDeviceChanges and fix JSRF now, or leave it with JSRF broken and spend (possibly days or more) investigating and debugging.

Note: It's always possible to download previous builds to try JSRF

**Comment by PatrickvL** [comment] 2017-05-16 06:22
Maybe if it's detected in the wrong location, the OOVPA just needs to be extended?

**Comment by LukeUsher** [comment] 2017-05-16 06:23
It's not that simple, altering XGetDeviceChanges to always return no changes also fixes the JSRF crash... Except that breaks input in other titles

**Comment by PatrickvL** [comment] 2017-05-16 06:25
Btw: confirming XGetDeviceChanges is the cause, would be a simple matter of changing it's location to zero in the HLE cache file for JSRF

**Comment by jarupxx** [comment] 2017-05-16 11:49
Basically it seems that XGetDeviceChanges uses the same memory locate and stored *value is 0 or 1. However, the memory location of JSRF varies and the stored value is strange.

```
[0x1030] EmuXapi.cpp : EmuPatch_XGetDeviceChanges(
   DeviceType           : 001BC860
   pdwInsertions        : 0x7C0FB00 (*value: 0xCCCCCCCC)
   pdwRemovals          : 0x7C0FB04 (*value: 0xCCCCCCCC)
);
[0x1030] EmuXapi.cpp : EmuPatch_XGetDeviceChanges returns 1
[0x1030] EmuXapi.cpp : EmuPatch_XGetDeviceChanges(
   DeviceType           : 001BC860
   pdwInsertions        : 0x7C0FB18 (*value: 0x0)
   pdwRemovals          : 0x7C0FB1C (*value: 0x0)
);
[0x1030] EmuXapi.cpp : EmuPatch_XGetDeviceChanges returns 1
[0x1030] EmuXapi.cpp : EmuPatch_XGetDeviceChanges(
   DeviceType           : 001BC860
   pdwInsertions        : 0x7C0FB08 (*value: 0xCCCCCCCC)
   pdwRemovals          : 0x7C0FB0C (*value: 0x1)
);
[0x1030] EmuXapi.cpp : EmuPatch_XGetDeviceChanges returns 1
[0x1030] EmuXapi.cpp : EmuPatch_XGetDeviceChanges(
   DeviceType           : 001BC860
   pdwInsertions        : 0x7C0FB08 (*value: 0x1E0)
   pdwRemovals          : 0x7C0FB0C (*value: 0x93453674)
);
```

**Comment by LukeUsher** [comment] 2017-05-16 11:55
I'm going to do some real hardware testing to work out what should actually happen in all the XInput functions

**Comment by PatrickvL** [comment] 2017-05-16 16:57
I guess XGetDeviceChanges should initially zero out the values in *pdwInsertions and removals

**Comment by OlayColay** [comment] 2017-05-17 00:21
Alright, re-downloaded [this patch](https://ci.appveyor.com/project/SoullessSentinel/cxbx-reloaded/build/2ef0c0638f857affe8949ac846b6f099f700ab5b/job/o2ls07rpb8mvuie2/artifacts) and it's working fine again. Thanks everyone!

**Comment by ObiKKa** [comment] 2017-05-18 02:36
But that's an older update, OlayColay. I really need to point this to the team. But JSRF no longer works on the latest master (PR #469). Completely breaks. Same error message as in the first post's scan above.

**Comment by LukeUsher** [comment] 2017-06-28 09:09
#480 solved this via a game-specific hack, it will be solved properly by LLE of the OHCI interface, which will happen much later in development. (We're not quite ready for that just yet)

Closing this for now

**Closed by LukeUsher** 2017-06-28 09:09 UTC
