### ISSUE TITLE
Incompatibility with nxdk / pbkit

### ISSUE THREAD

**Issue by JayFoxRox** [Cxbx-Reloaded/Cxbx-Reloaded#1562] opened 2019-03-04 03:51 UTC
I have tried running https://github.com/Cxbx-Reloaded/xbox_kernel_test_suite in a fork based on Cxbx-Reloaded https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/0077eb7ab296a1636bac54f32fb44f6d2c35e3ae (so I was using a dirty version of that).

I was using nxdk https://github.com/XboxDev/nxdk/commit/d43bff7d0aea6837c9ab82bd071c35ce3d88608b and kernel-test suite https://github.com/Cxbx-Reloaded/xbox_kernel_test_suite/commit/ac5e9ee6a243a687cf8899762958f0e4c120001a.

However, the nxdk application does not run properly and seems to get stuck early-on.

Removal of this code worked around this issue:

```c
   switch(pb_init()){
        case 0: break;
        default:
            XSleep(2000);
            XReboot();
            return;
    }

    pb_show_debug_screen();
```

The nxdk sample code also appears to be affected.

I did not try to confirm using another revision and did not try to bisect.
However, @GXTX implicitly confirmed this issue, too.

I did not try to find out which line is the issue, but I currently assume that `pb_init` fails and returns a non-zero value.

**Comment by ergo720** [comment] 2021-05-22 10:05
I tested this again with https://github.com/Cxbx-Reloaded/xbox_kernel_test_suite/releases/tag/20200203162448-2587418 and https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/releases/tag/CI-5d222c1 and it worked fine now. I think this was caused by https://github.com/Cxbx-Reloaded/xbox_kernel_test_suite/issues/60, which was fixed in https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/1627 and again in https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/2171, so I'm tempted to close this.

**Comment by PatrickvL** [comment] 2021-05-22 11:03
Thanks for this concise summary, especially having links to exact versions and pull request is very informative. Closing this issue based on that is indeed appropriate.

**Closed** 2021-05-22 12:37 UTC
