### ISSUE TITLE
Namco Museum Regression

### ISSUE THREAD

**Issue by BenNottelling** [Cxbx-Reloaded/Cxbx-Reloaded#551] opened 2017-07-29 22:31 UTC
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1185315/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1185314/Xbe.txt)

Shows Namco logo, plays sound then crashes. Namco Museum 50th Anniversary does not crash though.
![capture](https://user-images.githubusercontent.com/17304943/28749147-e4470d10-7472-11e7-82be-81deca18d16c.PNG)
![capture2](https://user-images.githubusercontent.com/17304943/28749148-e449d932-7472-11e7-883c-264ca941f72a.PNG)

**Comment by PatrickvL** [comment] 2017-07-29 22:48
Are you sure this is not a duplicate of #265?

**Comment by BenNottelling** [comment] 2017-07-29 22:52
There is a comment about it, but the issue isn't the same

**Comment by PatrickvL** [comment] 2017-08-15 11:16
This issue was moved to Cxbx-Reloaded/game-compatibility#68

**Closed by PatrickvL** 2017-08-15 11:16 UTC
Labels: game-compatibility
