### ISSUE TITLE
Xbox One Controller D-pad not detected

### ISSUE THREAD

**Issue by ThatOneReaper** [Cxbx-Reloaded/Cxbx-Reloaded#155] opened 2017-02-08 16:09 UTC
When I try to map the D-pad on my controller to the respective inputs, the config menu does not detect it. All the other buttons and axes on the controller work.

It it helps, I suspect it might have to do with how the D-pad is handled on an Xbox One Controller (ex. Unity-based games treat it as a pair of axes).

**Comment by LukeUsher** [comment] 2017-02-08 16:14
This will likely be caused by the age of this project. The Cxbx input code is very old, it predates the existence of XInput on PC and uses the old DirectInput functionality.

It can be updated by reworking the input system to use a more modern alternative, but is low priority.

**Comment by BiatuAutMiahn** [comment] 2017-02-08 17:34
https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/28

**Comment by PatrickvL** [comment] 2017-02-09 08:45
Indeed, this is a complete duplicate of https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/28 and would be solved by https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/156

**Comment by LukeUsher** [comment] 2017-02-09 12:27
Closing due to duplication

**Closed by LukeUsher** 2017-02-09 12:27 UTC
Labels: duplicate
