### ISSUE TITLE
Remove duplicate Xbe.cpp file

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#552] opened 2017-07-29 22:46 UTC
Xbe.cpp appears twice in the src tree.
Refactor the code such, that one of these two can be removed.

**Comment by Luca1991** [comment] 2017-07-31 21:18
I always wanted to take part in this project, and I think that this issue is my best chance to jump in. Can I be assigned to this issue? I've a very busy life, but during weekends I've some free time.

**Comment by LukeUsher** [comment] 2017-07-31 21:20
Sure!

**Comment by Luca1991** [comment] 2017-07-31 21:27
@LukeUsher Thanks for the trust, I'll work on this ASAP.

**Comment by ergo720** [comment] 2017-07-31 21:46
I tried to build cxbx simply by removing this file and it builds fine but doesn't function properly: all the games fail to start with a black screen or an error regarding XInput not being initialized.

**Comment by Luca1991** [comment] 2017-07-31 21:48
@ergo720 ah, I've tried to compile cxbx without that file too, but I haven't tried to boot any games. Well I'll try to find any references then ;) Do you have any idea right now?

**Comment by PatrickvL** [comment] 2017-07-31 21:52
No need for code bloat, so anything not used could at least be ifdef-ed out. But indeed, do test no regressions occur because of it

**Comment by ergo720** [comment] 2017-07-31 22:02
The big difference between the two is that the core version has an overloaded constructor not present in the common version plus a lot of small differences in the other functions throughout the source.

**Comment by Luca1991** [comment] 2017-08-01 12:56
@ergo720 are you sure that building without \Common\Xbe.cpp CXBX will fail to start any game? I'm asking this because I've built it without this file and it still boots my games.
Right now I'm having a lot of issues booting games (the ones supposed to works), and the only title that goes ingame is "Frogger Beyond", but as far as I can tell, I haven't noticed any regression so far. 
I'll give it a closer look when I'll have some free time ;)

**Comment by PatrickvL** [comment] 2017-08-01 13:40
If I'm not mistaken, `Cxbx-Reloaded\src\Core\Xbe.cpp` can be deleted, while `Cxbx-Reloaded\src\Common\Xbe.cpp` should stay

**Comment by Luca1991** [comment] 2017-08-01 14:25
@PatrickvL yeah sorry, I was in rush and mistakenly written \Common instead of \Core. I've edited my previous message to avoid any confusion. As I've said, I tried to boot "Frogger Beyond" and it goes ingame without any regression. So, I'll give a closer look to \Core\Xbe.cpp to check if there are some useful functions to merge in \Common\Xbe.cpp and then I'll send a PR, ok?

**Comment by PatrickvL** [comment] 2017-08-01 15:35
@Luca1991 I _think_ the Common-version is best, and nothing from the Core-version is needed.

**Comment by ergo720** [comment] 2017-08-01 16:12
@Luca1991 I have rebuild cxbx without the core version and this time all my games work as before. I probably built the debug version the last time which is less compatible. So it's probably safe to just delete the core source

**Comment by Luca1991** [comment] 2017-08-01 22:27
Okay, I carefully compared the two files and as @ergo720 said earlier, the main difference is this unused constructor: `Xbe::Xbe(class Exe *x_Exe, const char *x_szTitle, bool x_bRetail)`.

I'm going to remove the file and send a PR. Thanks to all.

**Comment by PatrickvL** [comment] 2017-08-01 23:00
Fixed by PR #575

**Closed** 2017-08-01 22:59 UTC
Labels: good-for-beginners, help wanted, low-priority

**Comment by PatrickvL** [comment] 2017-08-03 22:24
@Luca1991 Could you check if both OpenXDK.cpp could be removed and/or merged too?

**Comment by Luca1991** [comment] 2017-08-03 22:58
@PatrickvL yes I'll check it, but right now I'm fixing issue  #574 (I'm at a good point anyway)
