### ISSUE TITLE
No visuals at all (black screen) in some titles

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [Cxbx-Reloaded/Cxbx-Reloaded#1263] opened 2018-06-08 09:17 UTC
Some titles show no visuals - you can navigate menus and some even play (judging by audible sound and log output). Also, the FPS counter shows that the game is rendering. Only, the screen stays black.

Post reports with titles here, with compatibility link to create relationship between issues, tracelogs also needed.

Same problem on
#1
* [187 Ride or Die](https://github.com/Cxbx-Reloaded/game-compatibility/issues/32)

#A
* [Apex Racing Evoluzione](https://github.com/Cxbx-Reloaded/game-compatibility/issues/775)
* [Auto Modellista](https://github.com/Cxbx-Reloaded/game-compatibility/issues/595)
* [Azurik: Rise of Perathia](https://github.com/Cxbx-Reloaded/game-compatibility/issues/444)

#B
* Baldur's Gate Dark Alliance 2
* Blinx 2
* [Brothers in Arms: Earned in Blood](https://github.com/Cxbx-Reloaded/game-compatibility/issues/309)
* [Burnout 2: Point of Impact](https://github.com/Cxbx-Reloaded/game-compatibility/issues/541)
* [Burnout 3: Takedown](https://github.com/Cxbx-Reloaded/game-compatibility/issues/375)
* [Burnout Revenge](https://github.com/Cxbx-Reloaded/game-compatibility/issues/192)

#C
* [Call of Duty 3](https://github.com/Cxbx-Reloaded/game-compatibility/issues/710)
* [Castlevania: Curse of Darkness](https://github.com/Cxbx-Reloaded/game-compatibility/issues/173)
* [Cel Damage](https://github.com/Cxbx-Reloaded/game-compatibility/issues/64)
* [CDX Forza Motorsports](https://github.com/Cxbx-Reloaded/game-compatibility/issues/627)
* Colin McRae Rally 2005
* Crash Nitro Kart
* [Crash Twinsanity](https://github.com/Cxbx-Reloaded/game-compatibility/issues/158) (goes in game but only HUD visible, tested by me.)
* [Crazy Taxi 3: High Roller](https://github.com/Cxbx-Reloaded/game-compatibility/issues/570)
* [Curious George](https://github.com/Cxbx-Reloaded/game-compatibility/issues/672)

#D
* [Dance Dance Revolution Ultramix 3](https://github.com/Cxbx-Reloaded/game-compatibility/issues/480)
* [Destroy All Humans!](https://github.com/Cxbx-Reloaded/game-compatibility/issues/540)
* [Doom 3](https://github.com/Cxbx-Reloaded/game-compatibility/issues/863)

#E
* [EA Sports F1 2002](https://github.com/Cxbx-Reloaded/game-compatibility/issues/77)
* Enclave (both retail and beta-version)
* [ESPN NBA BASKETBALL](https://github.com/Cxbx-Reloaded/game-compatibility/issues/607)
* [ESPN NFL 2K5](https://github.com/Cxbx-Reloaded/game-compatibility/issues/608)
* Euro 2004
* [Evil Dead A Firstful of A Boomstick](https://github.com/Cxbx-Reloaded/game-compatibility/issues/360)

#F
* [Fahrenheit](https://github.com/Cxbx-Reloaded/game-compatibility/issues/445)
* [Fallout Brotherhood of Steel](https://github.com/Cxbx-Reloaded/game-compatibility/issues/841)
* [Family Guy](https://github.com/Cxbx-Reloaded/game-compatibility/issues/762)

#G
* [Ghost Master](https://github.com/Cxbx-Reloaded/game-compatibility/issues/464)
* [Grabbed by The Ghoulies](https://github.com/Cxbx-Reloaded/game-compatibility/issues/873)

#H
* [Halo](https://github.com/Cxbx-Reloaded/game-compatibility/issues/95) *Cause: Broken Fog. Hack/Workaround: Ignore D3DRS_FOGENABLE*
* [Halo: Combat Evolved Demo](https://github.com/Cxbx-Reloaded/game-compatibility/issues/773)
* [Halo, Exhibition Demo Disc](https://github.com/Cxbx-Reloaded/game-compatibility/issues/882)
* Halo 2

#L
* Legend of Spyro

#M
* [Mad Dash Racing](https://github.com/Cxbx-Reloaded/game-compatibility/issues/456#issuecomment-388583803)
* [Mat Hoffman's Pro BMX 2](https://github.com/Cxbx-Reloaded/game-compatibility/issues/803) (gray, not black)
* Medal of Honor: European Assault
* Midtown Madness
* [Midtown Madness 3](https://github.com/Cxbx-Reloaded/game-compatibility/issues/725#issuecomment-395934447)
* [Mojo!](https://github.com/Cxbx-Reloaded/game-compatibility/issues/325)
* [Monopoly Party](https://github.com/Cxbx-Reloaded/game-compatibility/issues/653)
* [MVP Baseball 2005](https://github.com/Cxbx-Reloaded/game-compatibility/issues/612)
* [MX Unleashed](https://github.com/Cxbx-Reloaded/game-compatibility/issues/801)

#N
* [NBA LIVE 07](https://github.com/Cxbx-Reloaded/game-compatibility/issues/615)
* Need for speed most wanted
* [Need for Speed: Underground 2](https://github.com/Cxbx-Reloaded/game-compatibility/issues/83)
* Ninja Gaiden
* [NFL Fever 2004](https://github.com/Cxbx-Reloaded/game-compatibility/issues/613)
* [NHL 2K7](https://github.com/Cxbx-Reloaded/game-compatibility/issues/614)

#O
* [Oddworld: Munch's Oddysee](https://github.com/Cxbx-Reloaded/game-compatibility/issues/678)
* [Oddworld: Munch's Oddysee](https://github.com/Cxbx-Reloaded/game-compatibility/issues/543)

#P
* [Phantom Crash](https://github.com/Cxbx-Reloaded/game-compatibility/issues/618)
* [Pinball Hall of Fame](https://github.com/Cxbx-Reloaded/game-compatibility/issues/674)
* [Prince of Persia: The Sands of Time](https://github.com/Cxbx-Reloaded/game-compatibility/issues/396#issuecomment-389598160)
* [Prince of Persia: The Two Thrones](https://github.com/Cxbx-Reloaded/game-compatibility/issues/397)
* [PRO TENNIS WTA TOUR](https://github.com/Cxbx-Reloaded/game-compatibility/issues/527)
* [Project Gotham Racing 2](https://github.com/Cxbx-Reloaded/game-compatibility/issues/429)
* [Project Gotham Racing 2 Trial Version](https://github.com/Cxbx-Reloaded/game-compatibility/issues/430)
* Project Velocity

#R
* [R-Racing Evolution](https://github.com/Cxbx-Reloaded/game-compatibility/issues/804)
* [RalliSport Challenge 2](https://github.com/Cxbx-Reloaded/game-compatibility/issues/526)
* [Red Dead Revolver](https://github.com/Cxbx-Reloaded/game-compatibility/issues/795)

#S
* [Samurai ShoDown V](https://github.com/Cxbx-Reloaded/game-compatibility/issues/891)
* SEGA GT 2002
* [Serious Sam 2](https://github.com/Cxbx-Reloaded/game-compatibility/issues/705)
* [settings_adoc](https://github.com/Cxbx-Reloaded/game-compatibility/issues/589)
* [Shadow the Hedgehog](https://github.com/Cxbx-Reloaded/game-compatibility/issues/522)
* [Shadow the Hedgehog](https://github.com/Cxbx-Reloaded/game-compatibility/issues/476) (duplicated but different behaviour.)
* [Shark Tale](https://github.com/Cxbx-Reloaded/game-compatibility/issues/601)
* [Ski Racing 2005](https://github.com/Cxbx-Reloaded/game-compatibility/issues/523)
* Soldier of Fortunes 2
* [Soulcalibur II](https://github.com/Cxbx-Reloaded/game-compatibility/issues/467)
* [Spider-Man](https://github.com/Cxbx-Reloaded/game-compatibility/issues/442)
* [Spider-Man 2](https://github.com/Cxbx-Reloaded/game-compatibility/issues/596)
* [Spongebob Squarepants: Lights, Camera, Pants!](https://github.com/Cxbx-Reloaded/game-compatibility/issues/847)
* [Splinter Cell Double Agent](https://github.com/Cxbx-Reloaded/game-compatibility/issues/448)
* [SSX 3](https://github.com/Cxbx-Reloaded/game-compatibility/issues/798)
* [SSX Tricky](https://github.com/Cxbx-Reloaded/game-compatibility/issues/799)
* [SSX On Tour](https://github.com/Cxbx-Reloaded/game-compatibility/issues/812)
* [Star Wars: Jedi Knight II: Jedi Outcast](https://github.com/Cxbx-Reloaded/game-compatibility/issues/665)
* [Steel Battalion](https://github.com/Cxbx-Reloaded/game-compatibility/issues/354#issuecomment-395927085)
* [Stubbs the Zombie ](https://github.com/Cxbx-Reloaded/game-compatibility/issues/545)
* [Super Monkey Ball Delux](https://github.com/Cxbx-Reloaded/game-compatibility/issues/193)

#T
* [Tao Feng Fist Of The Lotus](https://github.com/Cxbx-Reloaded/game-compatibility/issues/602)
* [The Matrix: Path of Neo](https://github.com/Cxbx-Reloaded/game-compatibility/issues/868)
* [The Warriors](https://github.com/Cxbx-Reloaded/game-compatibility/issues/632)
* [The Sims 2](https://github.com/Cxbx-Reloaded/game-compatibility/issues/546)
* [The Lord of the Rings: The Two Towers](https://github.com/Cxbx-Reloaded/game-compatibility/issues/79)
* [TimeSplitters: Future Perfect](https://github.com/Cxbx-Reloaded/game-compatibility/issues/854)
* [TimeSplitters 2 Release, Exhibition Demo Disc](https://github.com/Cxbx-Reloaded/game-compatibility/issues/888)
* [Tom Clancy's Ghost Recon Advanced Warfighter](https://github.com/Cxbx-Reloaded/game-compatibility/issues/877)
* [Tony Hawk's American Wasteland](https://github.com/Cxbx-Reloaded/game-compatibility/issues/862)

#U
* [UEFA Euro 2004](https://github.com/Cxbx-Reloaded/game-compatibility/issues/781) - here is trace log, logged during loading screens, its enough for issue : [Euro2004_missinggfx_KrnlDebug.zip](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/2083772/Euro2004_missinggfx_KrnlDebug.zip)
* [Urban Chaos Riot Response](https://github.com/Cxbx-Reloaded/game-compatibility/issues/818)

#V
* [Voodoo Vince](https://github.com/Cxbx-Reloaded/game-compatibility/issues/177)

#W
* World Championship Pool 2004
* [Worms 3D Special Edition](https://github.com/Cxbx-Reloaded/game-compatibility/issues/646#issuecomment-389952445)
* WWE Raw 2 *(Cause: Pixel Shader related)*

#X
* X-men 
* [XGRA](https://github.com/Cxbx-Reloaded/game-compatibility/issues/791)

**Comment by PatrickvL** [comment] 2018-06-08 09:28
One attempt to fix this was https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1261 (but alas, it didn't help getting visuals restored)

**Comment by PatrickvL** [comment] 2018-06-08 09:28
Another attempt to fix this is https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/1264 - results pending

**Comment by Ale100000** [comment] 2018-06-08 15:52
Same problem on
[Destroy All Humans](https://github.com/Cxbx-Reloaded/game-compatibility/issues/540)
[Evil Dead A Firstful of A Boomstick](https://github.com/Cxbx-Reloaded/game-compatibility/issues/360)

**Comment by gandalfthewhite19890404** [comment] 2018-06-09 04:43
**Prince of Persia Sands of Time**
https://github.com/Cxbx-Reloaded/game-compatibility/issues/396

**Comment by gandalfthewhite19890404** [comment] 2018-06-09 15:01
World Championship Pool 2004 - there was not black screen, it was bright blue.

**Comment by Voxel9** [comment] 2018-06-10 08:50
[Mad Dash Racing](https://github.com/Cxbx-Reloaded/game-compatibility/issues/456) also doesn't display any visuals. Same with [Worms 3D SE](https://github.com/Cxbx-Reloaded/game-compatibility/issues/646), though it displays a blue-ish screen in-menus, and a different solid colour in-game depending on the map you're playing.
(Both games still have working audio and interaction)

**Comment by Stonos** [comment] 2018-06-10 17:41
Same issue with [XGRA](https://github.com/Cxbx-Reloaded/game-compatibility/issues/791).

**Comment by PatrickvL** [comment] 2018-06-11 17:48
From discord: are a lot of games just not displaying anything right now? I got Phantom Crash running (Both the 'orig' and normal xbe) and I can hear my way through menus but there's diddly-squat on screen. Had similar luck with X-men and Baldur's Gate Dark Alliance 2.

**Comment by Ale100000** [comment] 2018-06-13 02:44
Add 187 Ride or Die To the List
https://www.youtube.com/watch?v=vLwLyPQsPbk

**Comment by Eurose209** [comment] 2018-06-13 22:28
[Burnout 3: Takedown](https://github.com/Cxbx-Reloaded/game-compatibility/issues/375) and [Burnout Revenge](https://github.com/Cxbx-Reloaded/game-compatibility/issues/192) also have this issue.

**Comment by RadWolfie** [comment] 2018-07-02 02:22
User from discord report:
> Project Velocity has a black screen issue. After the logos get done showing up, everything works except the screen. The screen is black btw.

**Comment by medievil1** [comment] 2018-07-02 04:10
from my experience, some games NOW have black screen with the render directly to host backbuffer speed hack... (videos in broken sword, for example) turning it off restores visuals.. so people might want to make sure they check with it off and on....

**Comment by T02my** [comment] 2018-07-02 17:57
Soldier of Fortunes 2 too has black screen problem. In the logs it says:

[0x1AB8] WARN: RenderState_Simple(0x00040338 (D3DRS_SOLIDOFFSETENABLE), 0x00000000) is unsupported!
[0x1AB8] WARN: RenderState_Simple(0x00040338 (D3DRS_SOLIDOFFSETENABLE), 0x00000001) is unsupported!
[0x1AB8] WARN: RenderState_Simple(0x00040388 (D3DRS_POLYGONOFFSETZOFFSET), 0xC0000000) is unsupported!
[0x1AB8] WARN: RenderState_Simple(0x00040384 (D3DRS_POLYGONOFFSETZSLOPESCALE), 0xBF800000) is unsupported!
[0x1AB8] WARN: RenderState_Simple(0x00040338 (D3DRS_SOLIDOFFSETENABLE), 0x00000000) is unsupported!
[0x1AB8] WARN: RenderState_Simple(0x00040338 (D3DRS_SOLIDOFFSETENABLE), 0x00000001) is unsupported!
[0x1AB8] WARN: RenderState_Simple(0x00040388 (D3DRS_POLYGONOFFSETZOFFSET), 0xC0000000) is unsupported!
[0x1AB8] WARN: RenderState_Simple(0x00040384 (D3DRS_POLYGONOFFSETZSLOPESCALE), 0xBF800000) is unsupported!
[0x1AB8] WARN: RenderState_Simple(0x00040338 (D3DRS_SOLIDOFFSETENABLE), 0x00000000) is unsupported!
[0x1AB8] WARN: RenderState_Simple(0x00040338 (D3DRS_SOLIDOFFSETENABLE), 0x00000001) is unsupported!
[0x1AB8] WARN: RenderState_Simple(0x00040388 (D3DRS_POLYGONOFFSETZOFFSET), 0xC0000000) is unsupported!
[0x1AB8] WARN: RenderState_Simple(0x00040384 (D3DRS_POLYGONOFFSETZSLOPESCALE), 0xBF800000) is unsupported!
[0x1AB8] WARN: RenderState_Simple(0x00040338 (D3DRS_SOLIDOFFSETENABLE), 0x00000000) is unsupported!

**Comment by Ale100000** [comment] 2018-07-05 23:36
More games with black screen issue
[Call of Duty 3](https://github.com/Cxbx-Reloaded/game-compatibility/issues/710)
[Halo](https://github.com/Cxbx-Reloaded/game-compatibility/issues/95)
[Fallout Brotherhood of Steel](https://github.com/Cxbx-Reloaded/game-compatibility/issues/841)

**Comment by AzurikRiseOfPerathia** [comment] 2018-07-06 00:10
[Azurik: Rise of Perathia](https://github.com/Cxbx-Reloaded/game-compatibility/issues/444)

**Comment by Tex236** [comment] 2018-07-08 03:38
Another game with black screen issue
Crash Nitro Kart
Game intro and menu work however when starting to race its just black

**Comment by JohnGodgames** [comment] 2018-07-08 09:29
@AzurikRiseOfPerathia for Azurik: Rise of Perathia disable pixel shader (hack) helps to rendering.

**Comment by T02my** [comment] 2018-07-26 19:36
Black screen issue appears with Enclave (both retail and beta-version)

**Comment by mkultimate** [comment] 2018-08-15 16:57
other games with black screen
Grabbed By The Ghoulies
Castlevania Curse of Darkness

**Comment by Cade-H** [comment] 2018-08-19 01:13
Crazy Taxi 3 also has this issue.

**Comment by FabxBs** [comment] 2018-08-22 17:44
Splinter cell double agent has this issue too, since in non-wireframe mode only the HUD is visible, the rest has black screen, kinda of texture filter.

**Comment by FabxBs** [comment] 2018-08-23 20:12
Add Splinter Cell Double Agent to the issue, you can hear intro/logo but you can't see any of them, black screen only, also in menu you can see only the menu options, but no background animations and videos.

**Comment by andrewfree** [comment] 2018-09-07 03:34
halo 2

**Comment by AzurikRiseOfPerathia** [comment] 2018-09-07 07:10
@JohnGodgames 
it does not work I tried everything

**Comment by AzurikRiseOfPerathia** [comment] 2018-10-15 22:46
Once version 0.2 Alpha it is very important to fix all the problem related to the black screens in a Pull Requests for the official version 0.2. would seem to be a good solution. Like that once the release version 0.2 allows us all to relaunch the emulator in a hype, for a planning of the version 0.3, and who says we can discover it again passionate who will want to contribute;)

**Comment by gandalfthewhite19890404** [comment] 2018-10-17 10:35
I made some debug by PIC:
missing menu (black overlay above it) cause by SetRenderTarget call, you can see it on screenshot.
![menu_black](https://user-images.githubusercontent.com/24764335/47080632-36c5a680-d211-11e8-80ab-f96eb15010c7.png)

Last successed call is on screenshot too below:
![menu_render](https://user-images.githubusercontent.com/24764335/47080692-5c52b000-d211-11e8-8779-f6d7424bc850.png)

Here is some intermediate frame just before SetRenderTarget call - nice, isn't it (you can't get it even without pixel shaders):
![intermediatepic1](https://user-images.githubusercontent.com/24764335/47080763-85734080-d211-11e8-9389-0413fe0205e9.jpg)

**Comment by LukeUsher** [comment] 2018-10-17 10:58
Updated the first post to add the cause of the blackscreen in Halo.
Causes for blackscreen in other titles will be added as a case-by-case basis

**Comment by jizuz12** [comment] 2019-04-20 20:49
Grabbed By The Ghoulies yeah blackscreen and i really want to play
Its going to be fixed?

**Comment by PatrickvL** [comment] 2019-04-20 21:45
@jizuz12 You didn't report anything new, so your comment will be deleted shortly to keep the issue tracker clean. As for your question: it's better to visit our discord and ask for help or information there. This is an open source project, so anyone, you included, is welcome to contribute and improve the emulation. That's actually the best way to get your wish come true.

**Comment by FabxBs** [comment] 2019-04-29 19:34
I've done a multiple testing about these titles that shows black screen, and all of them has the same cause of the issue. So far the black screen is made by a surface wich isn't lockable, this generates the error [0x1104] WARN : D3D8    Locking host Surface failed!  Some games has these errors too:
  [0x3448] WARN : D3D8    Locking host CubeTexture failed!
[0x3448] WARN : D3D8    Locking host Texture failed! 
Wich can be related to this issue,

https://cdn.discordapp.com/attachments/481567264395755523/571815064672403475/unknown.png
This image indicates the actual behaviour of the emulator while it attempts to lock the surface, need to find out for each game the flags that are generated and in wich memory pool are allocated, When you read the CreateTexture API docs, you'll see which memory regions are lockable
So if the wrong pool was used, the resource can't get locked. Hope these info's will be useful for someone to test this out.

**Comment by FabxBs** [comment] 2019-05-03 14:42
https://github.com/Cxbx-Reloaded/game-compatibility/issues/868 new title found with this behaviour.

**Comment by Dogway** [comment] 2019-06-17 12:02
Two more titles:
Blinx 2
Ninja Gaiden

**Comment by AzurikRiseOfPerathia** [comment] 2019-10-13 12:25
I'm back. I think I found the source of the problem for the game Azurik: Rise of Perathia. I succeeded by a manipulation of the start button and A without displaying the backup menu in the title screen accessed directly to the training area.

The game and SUPER CLEAN! (except lag that is not disabling)

When we pass the door or we follow the tutorial the beginning of the film does not start black screens, Yesterday by wanting to find the source of the problem at all costs, I have not a chance had the game without music or voice offn that the sound effects.

So I go to the door and there the game starts with the levels that starts.

So this would come from DirectSonds which causes some problem of black screens because other games listed below react similarly.

**Comment by LukeUsher** [comment] 2019-10-13 16:32
@AzurikRiseOfPerathia we know the problem with Azurik: there's an issue in our tracker for it here
https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1727

**Comment by qholness** [comment] 2019-12-18 15:16
**Kung Fu Chaos** is also completely black.

**Comment by desapoint** [comment] 2020-02-26 18:32
**Mechassault 2 - Lone Wolf** is also completely black.

**Comment by marlonluft** [comment] 2020-04-20 02:30
**Midnight Club 3 DUB Edition Remix** has a blank square over the main menu, but i can see the background changing.

![blank](https://user-images.githubusercontent.com/10707753/79708344-89b06c00-8295-11ea-9229-d88b8edd4d27.png)

**Comment by Morsmalleo** [comment] 2020-10-08 10:08
Same problem with Whacked! Blank screen, sound in and out as well, sounds very glitchy to

**Comment by CodeGordon** [comment] 2020-10-18 15:16
This could be related to what I've been seeing in [Metal Dungeon](https://github.com/Cxbx-Reloaded/game-compatibility/issues/463). The symptoms are similar, but I'm not sure if the cause is the same.

**Comment by ObiKKa** [comment] 2020-11-30 22:53
The demo version of the game, Grabbed by the Ghoulies, also has this same problem as the full release.
- [Grabbed by the Ghoulies demo](https://github.com/Cxbx-Reloaded/game-compatibility/issues/1064#issue-753766514) (Called _"Ghoulies Demo"_. [Exhibition Demo Disc (vol 4)](http://xbox.gamespy.com/xbox/xbox-exhibition-vol-4/).)

**Comment by artiks12** [comment] 2021-01-29 19:00
Add NHL 2002 to the list

**Comment by ergo720** [comment] 2021-01-30 10:47
I'm closing and locking this issue, since it just says that a bunch of games have a black screen issue, which is too vague because that can have multiple different causes. Plus, the list is probably outdated anyway, since the issue was created 3 years ago and it's doubtful that someone tests the list with every new update of cxbxr.

PS: the first Midtown Madness isn't even an xbox game, it's for Microsoft Windows.

**Closed by ergo720** 2021-01-30 10:47 UTC
Labels: HLE, graphics, high-priority
