### ISSUE TITLE
007 agent under fire

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/Cxbx-Reloaded#608] opened 2017-08-04 21:13 UTC
<img width="479" alt="agent under fire" src="https://user-images.githubusercontent.com/26704355/28987171-2e593dfa-7938-11e7-8446-62573cf5ca16.PNG">

**Comment by BenNottelling** [comment] 2017-08-05 05:48
Duplicate of #607 ..also not a useful report

**Closed** 2017-08-05 07:24 UTC
