### ISSUE TITLE
[PAL] Rallisport Challenge crashes at loading screen

### ISSUE THREAD

**Issue by rexcaptain501** [Cxbx-Reloaded/Cxbx-Reloaded#500] opened 2017-07-12 23:16 UTC
Tested on Cxbx-Reloaded build 85c06590, Jul 11 2017

The game throws a few ignore-able XMountUtilityDrive errors, and when all four are ignored the game crashes.

Error 1: ![rsc error](https://user-images.githubusercontent.com/10300935/28143820-c98c75dc-67bb-11e7-98ac-8339dfe0cac0.PNG)

Error 2: ![rsc error 2](https://user-images.githubusercontent.com/10300935/28143829-d519510e-67bb-11e7-9fb3-bcb3010ace56.PNG)

Error 3: ![rsc error 3](https://user-images.githubusercontent.com/10300935/28143833-db8b285a-67bb-11e7-8d0b-b28f3f26d544.PNG)

Error 4: ![rsc error 4](https://user-images.githubusercontent.com/10300935/28143837-e23c570a-67bb-11e7-895d-ac1a43ce5d53.PNG)

Crash: ![rsc crash](https://user-images.githubusercontent.com/10300935/28143842-e9f571b6-67bb-11e7-9e27-691eda8e7367.PNG)

.xbe dump: [Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1143578/Xbe.txt)

Kernel Debug file: [KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1143585/KrnlDebug.txt)

Settings used:
Display Adapter: NVIDIA GeForce GTX 1060 6GB
Direct3D Device: Direct3D HAL (Hardware Accelerated)
Video Resolution: Automatic (Default)

**Comment by PatrickvL** [comment] 2017-07-13 07:28
This looks like a duplicate of #311, but I'll let you be the judge of that

**Comment by rexcaptain501** [comment] 2017-07-13 07:43
Whoops, didn't catch that. Do you still want me to keep this open?

**Comment by PatrickvL** [comment] 2017-07-13 07:48
Better close this one, add anything new to the existing issue. Thanks

**Closed** 2017-07-13 08:38 UTC
