### ISSUE TITLE
Cache converted vertex buffers

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#1378] opened 2018-08-10 07:25 UTC
Vertex buffers are currently converted on every draw call. We used to have a cache for this, but it got broken during various refactorings.

For this issue, restore the cache on converted vertex buffers.

As with texture conversion, updated to Xbox buffer contents should trigger a new contain to the host compatible format.

**Comment by LukeUsher** [comment] 2018-08-10 07:26
duplicate of #1277

**Closed by LukeUsher** 2018-08-10 07:26 UTC
